#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT_DIR"

pass() { printf "%-36s PASS\n" "$1"; }
fail() { printf "%-36s FAIL\n" "$1"; }

status=0

run_check() {
  local label="$1"
  shift
  if "$@" >/tmp/agentos-signoff.out 2>/tmp/agentos-signoff.err; then
    pass "$label"
  else
    fail "$label"
    cat /tmp/agentos-signoff.err >&2 || true
    status=1
  fi
}

contains_check() {
  local label="$1"
  local file="$2"
  local pattern="$3"
  if rg -q -- "$pattern" "$file"; then
    pass "$label"
  else
    fail "$label"
    status=1
  fi
}

echo "Final Prototype Sign-off"
echo "========================="

run_check "acceptance_checks" scripts/acceptance_checks.sh
run_check "temp_artifact_cleanup_policy" python3 scripts/cleanup_temp_artifacts.py --json
run_check "build_artifact_cleanup_policy" python3 scripts/cleanup_build_artifacts.py --json
run_check "runtime_guidance_smoke" scripts/smoke_kernel_native_codex_runtime_policy.sh

contains_check "readme_engine_setup" README.md "setup-engine"
contains_check "readme_codex_kernel" README.md "set-engine codex"
contains_check "runbook_demo_flow" docs/runbooks/agentos-operations-runbook.md "One-command Demo Reproduction"
contains_check "runbook_failure_matrix" docs/runbooks/agentos-operations-runbook.md "Failure Matrix"
contains_check "runbook_regression" docs/runbooks/agentos-operations-runbook.md "Regression Checks"
contains_check "runbook_kernel_boot" docs/runbooks/agentos-operations-runbook.md "Kernel Boot Integration"
contains_check "runbook_installed_launcher_repo_root" docs/runbooks/agentos-operations-runbook.md "installed launcher repo-root smoke"
contains_check "runbook_kernel_shadow_diagnostics" docs/runbooks/agentos-operations-runbook.md "kernel_policy_shadow"
contains_check "runbook_kernel_bridge_diagnostics" docs/runbooks/agentos-operations-runbook.md "kernel_policy_bridge"
contains_check "runbook_kernel_health" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl health"
contains_check "reference_install_validation_contract" docs/reference/install-validation-contract.md "Install Validation Contract"
contains_check "reference_review_bundle_export_contract" docs/reference/review-bundle-export-contract.md "Review Bundle Export Contract"
contains_check "reference_agentos_session_contract" docs/reference/agentos-session-contract.md "AgentOS Session Contract"
contains_check "reference_mediation_coverage_contract" docs/reference/mediation-coverage-map-v1.md "Mediation Coverage Map v1"
contains_check "reference_appliance_lifecycle_contract" docs/reference/appliance-lifecycle-contract.md "Appliance Lifecycle Contract"
contains_check "reference_runtime_entry_contract" docs/reference/runtime-entry-contract.md "Runtime Entry Contract"
contains_check "reference_agentos_system_image_layout" docs/reference/agentos-system-image-layout-v1.md "# AgentOS System Image Layout v1"
contains_check "reference_agentos_slot_update_contract" docs/reference/agentos-slot-update-contract-v1.md "# AgentOS Slot Update Contract v1"
contains_check "reference_agentos_recovery_mode_contract" docs/reference/agentos-recovery-mode-contract-v1.md "# AgentOS Recovery Mode Contract v1"
contains_check "reference_agentos_state_partition_contract" docs/reference/agentos-state-partition-contract-v1.md "# AgentOS State Partition Contract v1"
contains_check "reference_agentos_image_release_identity" docs/reference/agentos-image-release-identity-v1.md "# AgentOS Image Release Identity v1"
contains_check "reference_slot_layout_realization" docs/reference/slot-layout-realization-v1.md "# Slot Layout Realization v1"
contains_check "reference_image_update_prototype" docs/reference/image-update-prototype-v1.md "# Image Update Prototype v1"
contains_check "reference_rollback_and_recovery_slot_logic" docs/reference/rollback-and-recovery-slot-logic-v1.md "# Rollback and Recovery Slot Logic v1"
contains_check "reference_post_stage24_roadmap_window" docs/reference/post-stage24-roadmap-window-v1.md "# Post-Stage-24 Roadmap Window v1"
contains_check "reference_remastered_boot_flow_proof" docs/reference/remastered-boot-flow-proof-v1.md "# Remastered Boot Flow Proof v1"
contains_check "reference_boot_target_activation_wiring" docs/reference/boot-target-activation-wiring-v1.md "# Boot Target Activation Wiring v1"
contains_check "reference_vm_first_screen_evidence_export" docs/reference/vm-first-screen-evidence-export-v1.md "# VM First-Screen Evidence Export v1"
contains_check "reference_next_boot_target_integration" docs/reference/next-boot-target-integration-v1.md "# Next-Boot Target Integration v1"
contains_check "reference_installed_slot_switch_evidence" docs/reference/installed-slot-switch-evidence-v1.md "# Installed Slot Switch Evidence v1"
contains_check "reference_stage26_closeout_memo" docs/reference/stage26-closeout-memo.md "# Stage 26 Closeout Memo"
contains_check "reference_post_stage26_roadmap_window" docs/reference/post-stage26-roadmap-window-v1.md "# Post-Stage-26 Roadmap Window v1"
contains_check "reference_remastered_vm_boot_checklist" docs/reference/remastered-vm-boot-checklist-v1.md "# Remastered VM Boot Checklist v1"
contains_check "reference_post_stage28_kernel_native_runtime_window" docs/reference/post-stage28-kernel-native-codex-runtime-window-v1.md "# Post-Stage-28 Kernel-Native Codex Runtime Window v1"
contains_check "reference_codex_primary_runtime_launch_path" docs/reference/codex-primary-runtime-launch-path-v1.md "# Codex Primary Runtime Launch Path v1"
contains_check "reference_codex_runtime_contract_freeze" docs/reference/codex-runtime-contract-freeze-v1.md "# Codex Runtime Contract Freeze v1"
contains_check "reference_codex_primary_runtime_proof" docs/reference/codex-primary-runtime-proof-v1.md "# Codex Primary Runtime Proof v1"
contains_check "reference_codex_launch_supervision" docs/reference/codex-launch-supervision-v1.md "# Codex Launch Supervision v1"
contains_check "reference_codex_recovery_to_codex" docs/reference/codex-recovery-to-codex-v1.md "# Codex Recovery To Codex v1"
contains_check "reference_runtime_health_evidence" docs/reference/runtime-health-evidence-v1.md "# Runtime Health Evidence v1"
contains_check "reference_stage30_closeout_memo" docs/reference/stage30-closeout-memo.md "# Stage 30 Closeout Memo"
contains_check "reference_issue_branch_lifecycle_policy" docs/reference/issue-branch-lifecycle-policy-v1.md "# Issue / Branch Lifecycle Policy v1"
contains_check "reference_kernel_native_codex_runtime_mvp_policy" docs/reference/kernel-native-codex-runtime-mvp-policy-v1.md "# Kernel-Native Codex Runtime MVP Policy v1"
contains_check "reference_temp_artifact_cleanup_policy" docs/reference/temp-artifact-cleanup-policy-v1.md "# Temp Artifact Cleanup Policy v1"
contains_check "reference_build_artifact_cleanup_policy" docs/reference/build-artifact-cleanup-policy-v1.md "# Build Artifact Cleanup Policy v1"
contains_check "agents_runtime_priority_lock" AGENTS.md "kernel-native Codex CLI runtime"
contains_check "prd_primary_runtime" PRD.md "primary managed runtime of AgentOS"
contains_check "tasks_shell_resemblance_guardrail" TASKS.md "no new phase should be opened for shell resemblance only"
contains_check "tasks_active_phase_179" TASKS.md "Phase 179 — Codex Runtime Contract Freeze"
contains_check "tasks_active_phase_180" TASKS.md "Phase 180 — Codex Primary Runtime Proof"
contains_check "tasks_active_phase_181" TASKS.md "Phase 181 — Codex Launch Supervision"
contains_check "tasks_active_phase_182" TASKS.md "Phase 182 — Recovery To Codex"
contains_check "tasks_active_phase_183" TASKS.md "Phase 183 — Runtime Health Evidence"
contains_check "tasks_current_active_none" TASKS.md "Current active phase:"
contains_check "next_roadmap_stage29" docs/next-roadmap.md "## Active Stage 29 — Codex CLI Primary Runtime"
contains_check "runbook_kernel_codex_primary_runtime" docs/runbooks/agentos-operations-runbook.md "codex-primary-runtime"
contains_check "runbook_kernel_codex_runtime_contract" docs/runbooks/agentos-operations-runbook.md "codex-runtime-contract"
contains_check "runbook_kernel_codex_primary_runtime_proof" docs/runbooks/agentos-operations-runbook.md "codex-primary-runtime-proof"
contains_check "runbook_kernel_codex_launch_supervision" docs/runbooks/agentos-operations-runbook.md "codex-launch-supervision"
contains_check "runbook_kernel_codex_recovery_to_codex" docs/runbooks/agentos-operations-runbook.md "codex-recovery-to-codex"
contains_check "runbook_kernel_codex_runtime_health_evidence" docs/runbooks/agentos-operations-runbook.md "codex-runtime-health-evidence"
contains_check "reference_operator_mode_contract" docs/reference/operator-mode-contract.md "Operator Mode Contract"
contains_check "reference_mediation_taxonomy_contract" docs/reference/mediation-taxonomy-v1.md "Mediation Taxonomy v1"
contains_check "reference_unified_event_schema_contract" docs/reference/unified-event-schema-v1.md "Unified Event Schema v1"
contains_check "reference_service_governance_contract" docs/reference/service-governance-model-v1.md "Service Governance Model v1"
contains_check "reference_automation_governance_contract" docs/reference/automation-governance-model-v1.md "Automation Governance Model v1"
contains_check "reference_policy_maturity_contract" docs/reference/policy-maturity-ladder-v1.md "Policy Maturity Ladder v1"
contains_check "reference_provenance_graph_contract" docs/reference/provenance-graph-v1.md "Provenance Graph v1"
contains_check "reference_user_space_sovereignty_contract" docs/reference/user-space-sovereignty-v1.md "User Space Sovereignty v1"
contains_check "reference_mediation_pilot_contract" docs/reference/mandatory-mediation-pilot-v1.md "Mandatory Mediation Pilot v1"
contains_check "reference_distribution_strategy_paper" docs/reference/distribution-strategy-paper-v1.md "Distribution Strategy Paper v1"
contains_check "reference_install_identity_native_session_ux" docs/reference/install-identity-native-session-ux-v1.md "Install Identity / Native Session UX Spec v1"
contains_check "reference_release_engineering_v1" docs/reference/release-engineering-v1.md "Release Engineering v1"
contains_check "reference_kernel_deepening_feasibility_v1" docs/reference/kernel-deepening-feasibility-v1.md "Kernel Deepening Feasibility v1"
contains_check "reference_platform_strategy_v1" docs/reference/platform-strategy-v1.md "Platform Strategy v1"
contains_check "reference_platform_validation_matrix_v1" docs/reference/platform-validation-matrix-v1.md "Platform Validation Matrix v1"
contains_check "reference_stage3_decision_pack_v1" docs/reference/stage3-decision-pack-v1.md "Stage 3 Decision Pack v1"
contains_check "reference_stage3_closeout_memo" docs/reference/stage3-closeout-memo.md "Stage 3 Closeout Memo"
contains_check "reference_public_milestone_bundle_contract" docs/reference/public-milestone-bundle-contract.md "Public Milestone Bundle Contract"
contains_check "reference_preview_release_candidate_checklist" docs/reference/preview-release-candidate-checklist-v1.md "Preview Release Candidate Checklist v1"
contains_check "reference_preview_release_note_template" docs/reference/preview-release-note-template-v1.md "Preview Release Note Template v1"
contains_check "reference_release_artifact_manifest_contract" docs/reference/release-artifact-manifest-contract-v1.md "Release Artifact Manifest Contract v1"
contains_check "reference_preview_evaluation_kit_contract" docs/reference/preview-evaluation-kit-contract-v1.md "Preview Evaluation Kit Contract v1"
contains_check "reference_evaluator_feedback_intake_contract" docs/reference/evaluator-feedback-intake-contract-v1.md "Evaluator Feedback Intake Contract v1"
contains_check "reference_external_evaluation_runbook_contract" docs/reference/external-evaluation-runbook-contract-v1.md "External Evaluation Runbook Contract v1"
contains_check "reference_preview_readiness_scorecard" docs/reference/preview-readiness-scorecard-v1.md "Preview Readiness Scorecard v1"
contains_check "reference_public_milestone_candidate" docs/reference/public-milestone-candidate-v1.md "Public Milestone Candidate v1"
contains_check "reference_stage4_closeout_memo" docs/reference/stage4-closeout-memo.md "Stage 4 Closeout Memo"
contains_check "runbook_kernel_audit" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl audit"
contains_check "runbook_kernel_audit_shadow" docs/runbooks/agentos-operations-runbook.md 'audit JSON includes `shadow_mode`'
contains_check "runbook_kernel_repair" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl repair"
contains_check "runbook_kernel_repair_dry_run" docs/runbooks/agentos-operations-runbook.md "--dry-run"
contains_check "runbook_kernel_repair_checks" docs/runbooks/agentos-operations-runbook.md "--checks"
contains_check "runbook_kernel_repair_report_file" docs/runbooks/agentos-operations-runbook.md "--report-file"
contains_check "runbook_kernel_repair_report_dir" docs/runbooks/agentos-operations-runbook.md "--report-dir"
contains_check "runbook_kernel_repair_report_retain" docs/runbooks/agentos-operations-runbook.md "--report-retain"
contains_check "runbook_kernel_report_status" docs/runbooks/agentos-operations-runbook.md "report-status"
contains_check "runbook_kernel_firstrun_reset" docs/runbooks/agentos-operations-runbook.md "firstrun-reset"
contains_check "runbook_kernel_status_json" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl status --workspace ./workspaces/default --json"
contains_check "runbook_kernel_workflow_status" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl workflow-status"
contains_check "runbook_kernel_session_contract" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl session-contract"
contains_check "runbook_kernel_mediation_coverage" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl mediation-coverage"
contains_check "runbook_kernel_appliance_lifecycle" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl appliance-lifecycle"
contains_check "runbook_kernel_runtime_entry" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl runtime-entry"
contains_check "runbook_kernel_system_image_layout" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl system-image-layout"
contains_check "runbook_kernel_slot_update_contract" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl slot-update-contract"
contains_check "runbook_slot_metadata_smoke" docs/runbooks/agentos-operations-runbook.md "smoke_agentos_slot_metadata.sh"
contains_check "runbook_image_update_prototype" docs/runbooks/agentos-operations-runbook.md "image-update-prototype"
contains_check "runbook_image_update_prototype_smoke" docs/runbooks/agentos-operations-runbook.md "smoke_kernel_image_update_prototype.sh"
contains_check "runbook_slot_recovery_logic" docs/runbooks/agentos-operations-runbook.md "slot-recovery-logic"
contains_check "runbook_slot_recovery_logic_smoke" docs/runbooks/agentos-operations-runbook.md "smoke_kernel_slot_recovery_logic.sh"
contains_check "runbook_verify_remastered_boot_flow" docs/runbooks/agentos-operations-runbook.md "smoke_verify_remastered_boot_flow.sh"
contains_check "runbook_verify_boot_target_activation" docs/runbooks/agentos-operations-runbook.md "boot-target-activation-wiring-v1.md"
contains_check "runbook_verify_vm_first_screen_evidence" docs/runbooks/agentos-operations-runbook.md "vm-first-screen-evidence-export-v1.md"
contains_check "runbook_next_boot_target_integration" docs/runbooks/agentos-operations-runbook.md "next-boot-target-integration-v1.md"
contains_check "runbook_installed_slot_switch_evidence" docs/runbooks/agentos-operations-runbook.md "installed-slot-switch-evidence-v1.md"
contains_check "runbook_stage26_closeout_memo" docs/runbooks/agentos-operations-runbook.md "stage26-closeout-memo.md"
contains_check "runbook_remastered_vm_boot_checklist" docs/runbooks/agentos-operations-runbook.md "remastered-vm-boot-checklist-v1.md"
contains_check "runbook_issue_branch_lifecycle_policy" docs/runbooks/agentos-operations-runbook.md "issue-branch-lifecycle-policy-v1.md"
contains_check "runbook_kernel_recovery_mode_contract" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl recovery-mode-contract"
contains_check "runbook_kernel_state_partition_contract" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl state-partition-contract"
contains_check "runbook_kernel_image_release_identity" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl image-release-identity"
contains_check "runbook_kernel_operator_mode" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl operator-mode"
contains_check "runbook_kernel_mediation_taxonomy" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl mediation-taxonomy"
contains_check "runbook_kernel_unified_event_schema" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl unified-event-schema"
contains_check "runbook_kernel_service_governance" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl service-governance"
contains_check "runbook_kernel_automation_governance" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl automation-governance"
contains_check "runbook_kernel_policy_maturity" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl policy-maturity"
contains_check "runbook_kernel_provenance_graph" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl provenance-graph"
contains_check "runbook_kernel_user_space_sovereignty" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl user-space-sovereignty"
contains_check "runbook_kernel_mediation_pilot" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl mediation-pilot"
contains_check "runbook_kernel_firstrun_wizard" docs/runbooks/agentos-operations-runbook.md "firstrun wizard smoke"
contains_check "runbook_local_llm_no_tui_smoke" docs/runbooks/agentos-operations-runbook.md "smoke_no_tui_fake_ollama.sh"
contains_check "runbook_kernel_root_guard" docs/runbooks/agentos-operations-runbook.md "root sessions stay on normal TTY shell"
contains_check "runbook_kernel_policy_bridge_cmd" docs/runbooks/agentos-operations-runbook.md "policy-bridge"
contains_check "runbook_kernel_policy_shadow_cmd" docs/runbooks/agentos-operations-runbook.md "policy-shadow"
contains_check "runbook_kernel_policy_enforce_cmd" docs/runbooks/agentos-operations-runbook.md "policy-enforce"
contains_check "runbook_kernel_policy_ready_cmd" docs/runbooks/agentos-operations-runbook.md "policy-ready"
contains_check "runbook_review_bundle_default_handoff" docs/runbooks/agentos-operations-runbook.md "default operator handoff artifact"
contains_check "runbook_review_bundle_latest_manifest" docs/runbooks/agentos-operations-runbook.md "latest-bundle-manifest.json"
contains_check "runbook_kernel_milestone_bundle" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl milestone-bundle"
contains_check "runbook_kernel_preview_eval_kit" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl preview-eval-kit"
contains_check "runbook_kernel_evaluator_cohort_pack" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl evaluator-cohort-pack"
contains_check "runbook_kernel_feedback_intake" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl feedback-intake"
contains_check "runbook_kernel_feedback_triage" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl feedback-triage"
contains_check "runbook_kernel_direct_boot_ux_burndown" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl direct-boot-ux-burndown"
contains_check "runbook_kernel_limited_preview_readiness" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl limited-preview-readiness"
contains_check "runbook_kernel_external_eval_checklist" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl external-eval-checklist"
contains_check "runbook_kernel_preview_readiness" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl preview-readiness"
contains_check "reference_preview_rehearsal_loop" docs/reference/preview-rehearsal-loop-v1.md "# Preview Rehearsal Loop v1"
contains_check "runbook_kernel_preview_rehearsal" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl preview-rehearsal"
contains_check "reference_preview_candidate_decision_pack" docs/reference/preview-candidate-decision-pack-v1.md "# Preview Candidate Decision Pack v1"
contains_check "runbook_kernel_preview_candidate" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl preview-candidate"
contains_check "reference_direct_ai_boot_contract" docs/reference/direct-ai-boot-contract-v1.md "# Direct AI Boot Contract v1"
contains_check "reference_direct_ai_boot_continue" docs/reference/direct-ai-boot-contract-v1.md "Continue to AgentOS"
contains_check "reference_live_appliance_session_contract" docs/reference/live-appliance-session-contract-v1.md "# Live Appliance Session Contract v1"
contains_check "reference_tiny_setup_then_ai_contract" docs/reference/tiny-setup-then-ai-contract-v1.md "# Tiny Setup Then AI Contract v1"
contains_check "reference_iso_entry_ux_wiring" docs/reference/iso-entry-ux-wiring-v1.md "# ISO Entry UX Wiring v1"
contains_check "reference_legacy_boot_compatibility_contract" docs/reference/legacy-boot-compatibility-contract-v1.md "# Legacy Boot Integration Compatibility Contract v1"
contains_check "reference_stage6_closeout_memo" docs/reference/stage6-closeout-memo.md "# Stage 6 Closeout Memo"
contains_check "reference_install_later_flow" docs/reference/install-later-flow-v1.md "# Install-Later Flow v1"
contains_check "reference_installed_appliance_session_contract" docs/reference/installed-appliance-session-contract-v1.md "# Installed Appliance Session Contract v1"
contains_check "reference_agentos_recovery_path_contract" docs/reference/agentos-recovery-path-contract-v1.md "# AgentOS Recovery Path Contract v1"
contains_check "reference_beginner_vm_onboarding_rewrite" docs/reference/beginner-vm-onboarding-rewrite-v1.md "# Beginner VM Onboarding Rewrite v1"
contains_check "reference_stage7_closeout_memo" docs/reference/stage7-closeout-memo.md "# Stage 7 Closeout Memo"
contains_check "reference_demo_evaluation_flow_reset" docs/reference/demo-and-evaluation-flow-reset-v1.md "# Demo and Evaluation Flow Reset v1"
contains_check "reference_stage8_closeout_memo" docs/reference/stage8-closeout-memo.md "# Stage 8 Closeout Memo"
contains_check "reference_post_stage8_roadmap_window" docs/reference/post-stage8-roadmap-window-v1.md "# Post-Stage-8 Roadmap Window v1"
contains_check "reference_evaluator_cohort_pack" docs/reference/evaluator-cohort-pack-v1.md "# Evaluator Cohort Pack v1"
contains_check "reference_feedback_triage_promotion_buckets" docs/reference/feedback-triage-promotion-buckets-v1.md "# Feedback Triage and Promotion Buckets v1"
contains_check "reference_direct_boot_ux_burndown" docs/reference/direct-boot-ux-burndown-v1.md "# Direct-Boot UX Burn-Down v1"
contains_check "reference_recovery_clarity_fix_loop" docs/reference/recovery-clarity-fix-loop-v1.md "# Recovery Clarity Fix Loop v1"
contains_check "reference_direct_boot_messaging_consistency" docs/reference/direct-boot-messaging-consistency-v1.md "# Direct-Boot Messaging Consistency v1"
contains_check "reference_limited_preview_iteration_ledger" docs/reference/limited-preview-iteration-ledger-v1.md "# Limited Preview Iteration Ledger v1"
contains_check "reference_broader_preview_readiness_scoreboard" docs/reference/broader-preview-readiness-scoreboard-v1.md "# Broader Preview Readiness Scoreboard v1"
contains_check "reference_broader_preview_launch_pack" docs/reference/broader-preview-launch-pack-v1.md "# Broader Preview Launch Pack v1"
contains_check "reference_stage12_closeout_memo" docs/reference/stage12-closeout-memo.md "# Stage 12 Closeout Memo"
contains_check "reference_post_stage12_roadmap_window" docs/reference/post-stage12-roadmap-window-v1.md "# Post-Stage-12 Roadmap Window v1"
contains_check "reference_stage68_operator_usability" docs/reference/stage68-operator-usability-consolidation-v1.md "# Stage 68 Operator Usability Consolidation v1"
contains_check "reference_recovery_rejoin_summary" docs/reference/recovery-rejoin-summary-v1.md "# Recovery Rejoin Summary v1"
contains_check "reference_recovery_copy_consistency" docs/reference/recovery-copy-consistency-v1.md "# Recovery Copy Consistency v1"
contains_check "reference_recovery_watch_reevaluation" docs/reference/recovery-watch-reevaluation-v1.md "# Recovery Watch Re-evaluation v1"
contains_check "reference_preview_posture_rescore" docs/reference/preview-posture-rescore-v1.md "# Preview Posture Re-score v1"
contains_check "reference_updated_broader_preview_launch_pack" docs/reference/updated-broader-preview-launch-pack-v1.md "# Updated Broader Preview Launch Pack v1"
contains_check "reference_broader_preview_cohort_operations" docs/reference/broader-preview-cohort-operations-v1.md "# Broader Preview Cohort Operations v1"
contains_check "reference_broader_preview_issue_ledger" docs/reference/broader-preview-issue-ledger-v1.md "# Broader Preview Issue Ledger v1"
contains_check "reference_broader_preview_health_summary" docs/reference/broader-preview-health-summary-v1.md "# Broader Preview Health Summary v1"
contains_check "reference_broader_preview_continuation_pack" docs/reference/broader-preview-continuation-pack-v1.md "# Broader Preview Continuation Pack v1"
contains_check "reference_public_preview_position_update" docs/reference/public-preview-position-update-v1.md "# Public Preview Position Update v1"
contains_check "reference_broader_preview_signal_snapshot" docs/reference/broader-preview-signal-snapshot-v1.md "# Broader Preview Signal Snapshot v1"
contains_check "reference_broader_preview_drift_ledger" docs/reference/broader-preview-drift-ledger-v1.md "# Broader Preview Drift Ledger v1"
contains_check "reference_broader_preview_weekly_summary" docs/reference/broader-preview-weekly-summary-v1.md "# Broader Preview Weekly Summary v1"
contains_check "reference_stage16_closeout_memo" docs/reference/stage16-closeout-memo.md "# Stage 16 Closeout Memo"
contains_check "reference_post_stage16_roadmap_window" docs/reference/post-stage16-roadmap-window-v1.md "# Post-Stage-16 Roadmap Window v1"
contains_check "reference_stage14_closeout_memo" docs/reference/stage14-closeout-memo.md "# Stage 14 Closeout Memo"
contains_check "reference_limited_preview_readiness_scoreboard" docs/reference/limited-preview-readiness-scoreboard-v1.md "# Limited Preview Readiness Scoreboard v1"
contains_check "reference_broader_preview_candidate_pack" docs/reference/broader-preview-candidate-pack-v1.md "# Broader Preview Candidate Pack v1"
contains_check "reference_stage10_closeout_memo" docs/reference/stage10-closeout-memo.md "# Stage 10 Closeout Memo"
contains_check "reference_post_stage10_roadmap_window" docs/reference/post-stage10-roadmap-window-v1.md "# Post-Stage-10 Roadmap Window v1"
contains_check "reference_post_stage14_roadmap_window" docs/reference/post-stage14-roadmap-window-v1.md "# Post-Stage-14 Roadmap Window v1"
contains_check "roadmap_completed_window_phase103_117" docs/roadmap.md '- Phase 103~117 defined in `docs/next-roadmap.md`'
contains_check "roadmap_completed_window_phase124_129" docs/roadmap.md '- Phase 124~129 defined in `docs/next-roadmap.md`'
contains_check "roadmap_completed_window_phase130_135" docs/roadmap.md '- Phase 130~135 defined in `docs/next-roadmap.md`'
contains_check "roadmap_completed_window_phase142_147" docs/roadmap.md '- Phase 142~147 defined in `docs/next-roadmap.md`'
contains_check "roadmap_completed_window_phase136_141" docs/roadmap.md '- Phase 136~141 defined in `docs/next-roadmap.md`'
contains_check "reference_public_preview_escalation_pack" docs/reference/public-preview-escalation-pack-v1.md "# Public Preview Escalation Pack v1"
contains_check "runbook_kernel_public_preview_escalation_pack" docs/runbooks/agentos-operations-runbook.md "public preview escalation pack contract"
contains_check "reference_public_preview_announcement_readiness" docs/reference/public-preview-announcement-readiness-v1.md "# Public Preview Announcement Readiness v1"
contains_check "runbook_kernel_public_preview_announcement_readiness" docs/runbooks/agentos-operations-runbook.md "public preview announcement readiness contract"
contains_check "reference_stage18_closeout" docs/reference/stage18-closeout-memo.md "# Stage 18 Closeout Memo"
contains_check "reference_post_stage18_window" docs/reference/post-stage18-roadmap-window-v1.md "# Post-Stage-18 Roadmap Window v1"
contains_check "reference_public_preview_decision_ledger" docs/reference/public-preview-decision-ledger-v1.md "# Public Preview Decision Ledger v1"
contains_check "runbook_kernel_public_preview_decision_ledger" docs/runbooks/agentos-operations-runbook.md "public preview decision ledger contract"
contains_check "reference_public_preview_messaging_review" docs/reference/public-preview-messaging-review-v1.md "# Public Preview Messaging Review v1"
contains_check "runbook_kernel_public_preview_messaging_review" docs/runbooks/agentos-operations-runbook.md "public preview messaging review contract"
contains_check "reference_public_preview_operating_brief" docs/reference/public-preview-operating-brief-v1.md "# Public Preview Operating Brief v1"
contains_check "runbook_kernel_public_preview_operating_brief" docs/runbooks/agentos-operations-runbook.md "public preview operating brief contract"
contains_check "reference_public_preview_decision_pack" docs/reference/public-preview-decision-pack-v1.md "# Public Preview Decision Pack v1"
contains_check "runbook_kernel_public_preview_decision_pack" docs/runbooks/agentos-operations-runbook.md "public preview decision pack contract"
contains_check "reference_public_preview_launch_readiness_review" docs/reference/public-preview-launch-readiness-review-v1.md "# Public Preview Launch Readiness Review v1"
contains_check "runbook_kernel_public_preview_launch_readiness_review" docs/runbooks/agentos-operations-runbook.md "public preview launch readiness review contract"
contains_check "reference_public_preview_go_no_go" docs/reference/public-preview-go-no-go-v1.md "# Public Preview Go/No-Go v1"
contains_check "runbook_kernel_public_preview_go_no_go" docs/runbooks/agentos-operations-runbook.md "public preview go/no-go contract"
contains_check "reference_stage20_closeout" docs/reference/stage20-closeout-memo.md "# Stage 20 Closeout Memo"
contains_check "runbook_kernel_broader_preview_candidate" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl broader-preview-candidate"
contains_check "runbook_kernel_recovery_clarity_fix_loop" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl recovery-clarity-fix-loop"
contains_check "runbook_kernel_direct_boot_messaging_consistency" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl direct-boot-messaging-consistency"
contains_check "runbook_kernel_limited_preview_iteration_ledger" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl limited-preview-iteration-ledger"
contains_check "runbook_kernel_broader_preview_readiness" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl broader-preview-readiness"
contains_check "runbook_kernel_broader_preview_launch_pack" docs/runbooks/agentos-operations-runbook.md "agentos-kernelctl broader-preview-launch-pack"
contains_check "runbook_kernel_updated_broader_preview_launch_pack" docs/runbooks/agentos-operations-runbook.md "updated-broader-preview-launch-pack"
contains_check "runbook_kernel_broader_preview_cohort_operations" docs/runbooks/agentos-operations-runbook.md "broader-preview-cohort-operations"
contains_check "runbook_kernel_broader_preview_issue_ledger" docs/runbooks/agentos-operations-runbook.md "broader-preview-issue-ledger"
contains_check "runbook_kernel_broader_preview_health_summary" docs/runbooks/agentos-operations-runbook.md "broader-preview-health-summary"
contains_check "runbook_kernel_broader_preview_continuation_pack" docs/runbooks/agentos-operations-runbook.md "broader-preview-continuation-pack"
contains_check "runbook_kernel_public_preview_position_update" docs/runbooks/agentos-operations-runbook.md "public-preview-position-update"
contains_check "runbook_kernel_broader_preview_signal_snapshot" docs/runbooks/agentos-operations-runbook.md "broader-preview-signal-snapshot"
contains_check "runbook_kernel_broader_preview_drift_ledger" docs/runbooks/agentos-operations-runbook.md "broader-preview-drift-ledger"
contains_check "runbook_kernel_broader_preview_weekly_summary" docs/runbooks/agentos-operations-runbook.md "broader-preview-weekly-summary"
contains_check "runbook_recovery_rejoin_summary" docs/runbooks/agentos-operations-runbook.md "AgentOS Recovery -> Return to AgentOS -> ai>"
contains_check "runbook_kernel_recovery_copy_consistency" docs/runbooks/agentos-operations-runbook.md "recovery-copy-consistency"
contains_check "runbook_kernel_recovery_watch_reevaluation" docs/runbooks/agentos-operations-runbook.md "recovery-watch-reevaluation"
contains_check "runbook_kernel_preview_posture_rescore" docs/runbooks/agentos-operations-runbook.md "preview-posture-rescore"
contains_check "runbook_kernel_policy_enforce_ready_smoke" docs/runbooks/agentos-operations-runbook.md "smoke_kernel_policy_enforce_require_ready.sh"
contains_check "runbook_iso_foundation" docs/runbooks/distribution-packaging-runbook.md "build_agentos_iso.sh"
contains_check "runbook_platform_reset_note" docs/runbooks/distribution-packaging-runbook.md "Platform reset note:"
contains_check "runbook_platform_reset_system_layout_ref" docs/runbooks/distribution-packaging-runbook.md "agentos-system-image-layout-v1.md"
contains_check "runbook_base_iso_fetch" docs/runbooks/distribution-packaging-runbook.md "fetch_ubuntu_base_iso.sh"
contains_check "runbook_vm_install_guide" docs/runbooks/distribution-packaging-runbook.md "vm-install-guide.md"
contains_check "readme_vm_install_guide" README.md "vm-install-guide.md"
contains_check "readme_base_iso_fetch" README.md "fetch_ubuntu_base_iso.sh"
contains_check "docs_index_vm_install_guide" docs/index.md "vm-install-guide.md"
contains_check "docs_index_vm_install_quickstart" docs/index.md "vm-install-quickstart.md"
contains_check "docs_index_issue_branch_lifecycle_policy" docs/index.md "issue-branch-lifecycle-policy-v1.md"
contains_check "readme_vm_install_quickstart" README.md "vm-install-quickstart.md"
contains_check "runbook_vm_install_quickstart" docs/runbooks/distribution-packaging-runbook.md "vm-install-quickstart.md"
contains_check "readme_fastest_vm_path" README.md "## Fastest VM Path"
contains_check "readme_brew_install_utm" README.md "brew install --cask utm"
contains_check "vm_quickstart_emulate_x86_64" docs/runbooks/vm-install-quickstart.md "Emulate -> x86_64"
contains_check "vm_guide_utm_homebrew" docs/runbooks/vm-install-guide.md "Install UTM with Homebrew:"
contains_check "packaging_runbook_advanced_fallback" docs/runbooks/distribution-packaging-runbook.md "This runbook is the advanced/fallback reference."
contains_check "vm_install_quickstart_success_path" docs/runbooks/vm-install-quickstart.md "AgentOS Setup -> AgentOS Managed Session -> ai>"
contains_check "vm_install_quickstart_recovery_summary" docs/runbooks/vm-install-quickstart.md "AgentOS Recovery -> Return to AgentOS -> ai>"
contains_check "vm_install_quickstart_iso_build" docs/runbooks/vm-install-quickstart.md "--download-base-image"
contains_check "vm_install_guide_utm" docs/runbooks/vm-install-guide.md "UTM on macOS"
contains_check "vm_install_guide_virtualbox" docs/runbooks/vm-install-guide.md "VirtualBox"
contains_check "vm_install_guide_success_path" docs/runbooks/vm-install-guide.md "AgentOS Setup -> AgentOS Managed Session -> ai>"
contains_check "vm_install_guide_recovery_summary" docs/runbooks/vm-install-guide.md "AgentOS Recovery -> Return to AgentOS -> ai>"
contains_check "readme_recovery_summary" README.md "AgentOS Recovery -> Return to AgentOS -> ai>"
contains_check "runbook_install_validation_contract" docs/runbooks/distribution-packaging-runbook.md "verify_install_validation_contract.py"
contains_check "runbook_install_verification_manifest" docs/runbooks/distribution-packaging-runbook.md "export_install_verification_manifest.py"
contains_check "runbook_preview_release_contract_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_preview_release_contract.sh"
contains_check "runbook_kernel_platform_validation" docs/runbooks/distribution-packaging-runbook.md "agentos-kernelctl platform-validation"
contains_check "runbook_deb_foundation" docs/runbooks/distribution-packaging-runbook.md "build_agentos_deb.sh"
contains_check "runbook_iso_asset_prepare" docs/runbooks/distribution-packaging-runbook.md "prepare_iso_assets.sh"
contains_check "runbook_iso_build_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_build_agentos_iso.sh"
contains_check "runbook_iso_package_policy" docs/runbooks/distribution-packaging-runbook.md "apt-packages.policy"
contains_check "runbook_iso_boot_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_agentos_iso_boot.sh"
contains_check "runbook_iso_metadata_gate" docs/runbooks/distribution-packaging-runbook.md "verify_iso_release_metadata.py"
contains_check "runbook_iso_postinstall_policy_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_iso_postinstall_policy.sh"
contains_check "runbook_kernel_policy_lock" docs/reference/kernel-policy-spec-lock.md "Kernel Policy Spec Lock"
contains_check "runbook_kernel_policy_export" docs/reference/kernel-policy-spec-lock.md "export_kernel_policy_spec.py"
contains_check "runbook_kernel_policy_bridge" docs/runbooks/kernel-policy-bridge-runbook.md "Kernel Policy Bridge Runbook"
contains_check "runbook_kernel_policy_bridge_signal" docs/runbooks/kernel-policy-bridge-runbook.md "destructive_action_approval"
contains_check "runbook_kernel_shadow_mode" docs/runbooks/kernel-shadow-mode-runbook.md "Kernel Shadow Mode Runbook"
contains_check "runbook_kernel_enforced_pilot" docs/runbooks/kernel-enforced-pilot-runbook.md "Kernel Enforced Pilot Runbook"
contains_check "runbook_kernel_recovery_smoke" docs/runbooks/kernel-enforced-pilot-runbook.md "smoke_kernel_policy_recovery.sh"
contains_check "runbook_vm_boot_chain" docs/runbooks/m5-substrate-runbook.md "smoke_vm_devcontainer_boot.sh"
contains_check "adr_kernel_mechanism_selection" docs/adr/0001-kernel-mechanism-selection.md "Primary mechanism: \\*\\*AppArmor\\*\\*"
contains_check "readme_iso_foundation" README.md "smoke_agentos_iso_layout.sh"
contains_check "readme_deb_foundation" README.md "build_agentos_deb.sh"
contains_check "readme_iso_asset_prepare" README.md "prepare_iso_assets.sh"
contains_check "readme_iso_build_smoke" README.md "smoke_build_agentos_iso.sh"
contains_check "readme_iso_metadata_gate" README.md "verify_iso_release_metadata.py"
contains_check "readme_local_llm_setup" README.md "ollama  \\(recommended\\)"
contains_check "reference_minimal_appliance_boot_screen" docs/reference/minimal-appliance-boot-screen-v1.md "# Minimal Appliance Boot Screen v1"
contains_check "runbook_minimal_appliance_boot_screen" docs/runbooks/agentos-operations-runbook.md "minimal appliance boot screen contract"
contains_check "runbook_boot_visual_contract" docs/runbooks/distribution-packaging-runbook.md 'grub_theme_contract = agentos_minimal_appliance_grub.v1'
contains_check "readme_boot_visual_sequence" README.md "expect an AgentOS-branded boot menu and minimal splash before setup"
contains_check "vm_quickstart_boot_visual_sequence" docs/runbooks/vm-install-quickstart.md "AgentOS boot menu"
contains_check "vm_install_guide_boot_visual_sequence" docs/runbooks/vm-install-guide.md "AgentOS minimal splash"
contains_check "docs_index_minimal_appliance_boot_screen" docs/index.md "minimal-appliance-boot-screen-v1.md"
contains_check "reference_post_stage20_roadmap_window" docs/reference/post-stage20-roadmap-window-v1.md "# Post-Stage-20 Roadmap Window v1"
contains_check "reference_live_iso_remaster_contract" docs/reference/live-iso-remaster-contract-v1.md "# Live ISO Remaster Contract v1"
contains_check "roadmap_active_window_phase154_165" docs/roadmap.md "- Phase 154~165 defined in `docs/next-roadmap.md`"
contains_check "roadmap_completed_window_phase148_153" docs/roadmap.md "- Phase 148~153 defined in `docs/next-roadmap.md`"
contains_check "next_roadmap_active_window_phase154_165" docs/next-roadmap.md "Active Phase 154~165 post-Stage-20 roadmap"
contains_check "next_roadmap_phase154_completed" docs/next-roadmap.md "fixed remaster environment and live asset injection contract in `docs/reference/live-iso-remaster-contract-v1.md`"
contains_check "next_roadmap_phase155_active" docs/next-roadmap.md "Phase 155 — ISO Remaster Pipeline"
contains_check "next_roadmap_stage21_active" docs/next-roadmap.md "- Stage 21 active"
contains_check "runbook_live_iso_remaster_contract" docs/runbooks/distribution-packaging-runbook.md "live-iso-remaster-contract-v1.md"
contains_check "readme_phase154_remaster_note" README.md "Phase 154 note:"
contains_check "reference_iso_remaster_pipeline" docs/reference/iso-remaster-pipeline-v1.md "# ISO Remaster Pipeline v1"
contains_check "next_roadmap_phase155_completed" docs/next-roadmap.md "remaster pipeline fixed in `docs/reference/iso-remaster-pipeline-v1.md`"
contains_check "reference_default_path_without_ubuntu_installer" docs/reference/default-path-without-ubuntu-installer-v1.md "# Default Path Without Ubuntu Installer v1"
contains_check "next_roadmap_phase156_completed" docs/next-roadmap.md "remastered boot entries now patch the visible default path to `Continue to AgentOS`, `Install AgentOS`, and `AgentOS Recovery`"
contains_check "reference_welcome_shell_app" docs/reference/welcome-shell-app-v1.md "# Welcome Shell App v1"
contains_check "next_roadmap_phase157_completed" docs/next-roadmap.md "the remastered live session now autostarts an AgentOS-owned welcome shell with `Continue to AgentOS`, `Install AgentOS`, and `Recovery`"
contains_check "reference_modern_network_step" docs/reference/modern-network-step-v1.md "# Modern Network Step v1"
contains_check "reference_welcome_to_setup_handoff" docs/reference/welcome-to-setup-handoff-v1.md "# Welcome-to-Setup Handoff v1"
contains_check "reference_install_later_productization" docs/reference/install-later-productization-v1.md "# Install-Later Productization v1"
contains_check "reference_writable_state_partition_foundation" docs/reference/writable-state-partition-foundation-v1.md "# Writable State Partition Foundation v1"
contains_check "reference_installed_appliance_boot_identity" docs/reference/installed-appliance-boot-identity-v1.md "# Installed Appliance Boot Identity v1"
contains_check "next_roadmap_phase158_completed" docs/next-roadmap.md "networking decisions for the default path now stay inside the AgentOS welcome shell with connect/skip/recovery actions"
contains_check "next_roadmap_phase159_completed" docs/next-roadmap.md "the welcome shell now records explicit AgentOS handoff routes for continue/install/recovery and return-to-setup"
contains_check "next_roadmap_phase160_completed" docs/next-roadmap.md "Install AgentOS now launches an AgentOS-owned persistence helper that writes an install request manifest and preserves installed_appliance_boot as the target origin"
contains_check "next_roadmap_phase161_completed" docs/next-roadmap.md "AgentOS now initializes a writable state root, exposes actual state-root usage through status/session surfaces, and preserves mutable data across repeated install-later preparation"
contains_check "next_roadmap_phase162_completed" docs/next-roadmap.md "installed appliance boot now writes an explicit installed-boot manifest and runtime surfaces report the same AgentOS-owned identity after persistence"
contains_check "next_roadmap_phase163_completed" docs/next-roadmap.md "Phase 163 completed"
contains_check "next_roadmap_phase164_completed" docs/next-roadmap.md "Phase 164 completed"
contains_check "next_roadmap_phase165_completed" docs/next-roadmap.md "Phase 165 completed"
contains_check "next_roadmap_phase166_completed" docs/next-roadmap.md "Phase 166 completed"
contains_check "next_roadmap_phase167_completed" docs/next-roadmap.md "Phase 167 completed"
contains_check "next_roadmap_phase168_completed" docs/next-roadmap.md "Phase 168 completed"
contains_check "next_roadmap_phase169_completed" docs/next-roadmap.md "Phase 169 completed"
contains_check "next_roadmap_phase170_completed" docs/next-roadmap.md "Phase 170 completed"
contains_check "next_roadmap_phase171_completed" docs/next-roadmap.md "Phase 171 completed"
contains_check "next_roadmap_phase172_completed" docs/next-roadmap.md "Phase 172 completed"
contains_check "next_roadmap_phase173_completed" docs/next-roadmap.md "Phase 173 completed"
contains_check "next_roadmap_phase174_completed" docs/next-roadmap.md "Phase 174 completed"
contains_check "next_roadmap_phase175_completed" docs/next-roadmap.md "Phase 175 completed"
contains_check "next_roadmap_phase176_completed" docs/next-roadmap.md "Phase 176 completed"
contains_check "next_roadmap_phase177_completed" docs/next-roadmap.md "Phase 177 completed"
contains_check "next_roadmap_no_active_window" docs/next-roadmap.md "No active next milestone is currently opened."
contains_check "runbook_iso_remaster_pipeline" docs/runbooks/distribution-packaging-runbook.md "iso-remaster-pipeline-v1.md"
contains_check "readme_phase155_note" README.md "Phase 155 note:"
contains_check "readme_phase156_note" README.md "Phase 156 note:"
contains_check "runbook_phase156_boot_patch_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_patch_agentos_boot_entries.sh"
contains_check "runbook_phase157_welcome_shell_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_agentos_welcome_shell.sh"
contains_check "runbook_phase158_welcome_network_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_agentos_welcome_network.sh"
contains_check "runbook_phase159_welcome_handoff_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_agentos_welcome_handoff.sh"
contains_check "runbook_phase160_install_productization_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_agentos_install_later_productization.sh"
contains_check "runbook_phase161_state_root_persistence_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_agentos_state_root_persistence.sh"
contains_check "runbook_phase162_installed_boot_identity_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_installed_appliance_boot_identity.sh"
contains_check "runbook_phase167_boot_target_activation_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_verify_boot_target_activation.sh"
contains_check "runbook_phase168_vm_first_screen_evidence_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_verify_vm_first_screen_evidence.sh"
contains_check "runbook_phase169_next_boot_target_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_kernel_next_boot_target_integration.sh"
contains_check "runbook_phase170_installed_slot_switch_evidence_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_kernel_installed_slot_switch_evidence.sh"
contains_check "runbook_phase172_remastered_vm_boot_checklist_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_kernel_remastered_vm_boot_checklist.sh"
contains_check "reference_welcome_first_vm_proof_pack" docs/reference/welcome-first-vm-proof-pack-v1.md "# Welcome-First VM Proof Pack v1"
contains_check "runbook_phase173_welcome_first_vm_proof_pack_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_kernel_welcome_first_vm_proof_pack.sh"
contains_check "reference_installed_reboot_slot_proof" docs/reference/installed-reboot-slot-proof-v1.md "# Installed Reboot Slot Proof v1"
contains_check "runbook_phase174_installed_reboot_slot_proof_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_kernel_installed_reboot_slot_proof.sh"
contains_check "reference_recovery_reentry_after_slot_switch" docs/reference/recovery-reentry-after-slot-switch-v1.md "# Recovery Re-entry After Slot Switch v1"
contains_check "runbook_phase175_recovery_reentry_after_slot_switch_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_kernel_recovery_reentry_after_slot_switch.sh"
contains_check "reference_appliance_boot_signoff_pack" docs/reference/appliance-boot-signoff-pack-v1.md "# Appliance Boot Signoff Pack v1"
contains_check "runbook_phase176_appliance_boot_signoff_pack_smoke" docs/runbooks/distribution-packaging-runbook.md "smoke_kernel_appliance_boot_signoff_pack.sh"
contains_check "reference_stage28_closeout_memo" docs/reference/stage28-closeout-memo.md "# Stage 28 Closeout Memo"
contains_check "acceptance_remastered_vm_boot_checklist_smoke" scripts/acceptance_checks.sh "smoke_kernel_remastered_vm_boot_checklist.sh"
contains_check "acceptance_welcome_first_vm_proof_pack_smoke" scripts/acceptance_checks.sh "smoke_kernel_welcome_first_vm_proof_pack.sh"
contains_check "acceptance_installed_reboot_slot_proof_smoke" scripts/acceptance_checks.sh "smoke_kernel_installed_reboot_slot_proof.sh"
contains_check "acceptance_recovery_reentry_after_slot_switch_smoke" scripts/acceptance_checks.sh "smoke_kernel_recovery_reentry_after_slot_switch.sh"
contains_check "acceptance_appliance_boot_signoff_pack_smoke" scripts/acceptance_checks.sh "smoke_kernel_appliance_boot_signoff_pack.sh"
contains_check "acceptance_work_item_lifecycle_smoke" scripts/acceptance_checks.sh "smoke_work_item_lifecycle.sh"
contains_check "acceptance_workflow_status_smoke" scripts/acceptance_checks.sh "smoke_kernel_workflow_status.sh"
contains_check "acceptance_telegram_thread_status_smoke" scripts/acceptance_checks.sh "smoke_kernel_telegram_thread_status.sh"
contains_check "acceptance_inbox_reply_workflow_smoke" scripts/acceptance_checks.sh "smoke_kernel_inbox_reply_workflow.sh"
contains_check "acceptance_research_brief_smoke" scripts/acceptance_checks.sh "smoke_kernel_research_brief.sh"
contains_check "acceptance_telegram_live_send_smoke" scripts/acceptance_checks.sh "smoke_kernel_telegram_live_send.sh"
contains_check "acceptance_telegram_live_loop_smoke" scripts/acceptance_checks.sh "smoke_kernel_telegram_live_loop.sh"
contains_check "acceptance_telegram_setup_smoke" scripts/acceptance_checks.sh "smoke_kernel_telegram_setup.sh"
contains_check "readme_issue_branch_workflow" README.md "issue-branch-lifecycle-policy-v1.md"

echo
if [ "$status" -eq 0 ]; then
  echo "Final sign-off: PASS"
else
  echo "Final sign-off: FAIL"
fi

exit "$status"
