#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import shutil
import subprocess
import sys
from pathlib import Path

ROOT_DIR = Path(__file__).resolve().parents[1]
SRC_DIR = ROOT_DIR / "src"
if str(SRC_DIR) not in sys.path:
    sys.path.insert(0, str(SRC_DIR))

from kernel.broker import append_broker_transition
from workspace.manager import WorkspaceManager


def _resolve_workspace_root(wm: WorkspaceManager) -> Path:
    root = Path(wm.workspace_root)
    if not root.is_absolute():
        root = (wm.workspace_dir / root).resolve()
    return root


def _template_text() -> str:
    return """# AgentOS kernel policy bridge template (Phase 40)
# Generated by scripts/kernel_policy_bridge.py
# This profile is scaffold output for shadow/passive validation.
# It is NOT enforced by default in v1.

#include <tunables/global>

profile agentos-kernel-policy flags=(attach_disconnected,mediate_deleted) {
  #include <abstractions/base>

  # Workspace boundary (resolved from runtime.workspace_root)
  owner __WORKSPACE_ROOT__/** rwk,

  # Outside workspace policy candidate (shadow in v1)
  # deny /** rwklx,

  # Browser allowlist candidate (comments only in v1 bridge output)
  # __BROWSER_ALLOWLIST__

  # Web allowlist candidate (comments only in v1 bridge output)
  # __WEB_ALLOWLIST__

  # Destructive-action approval signal candidate (comments only in v1 bridge output)
  # __DESTRUCTIVE_ACTION_SIGNAL__
}
"""


def _render_comment_lines(values: list[str], prefix: str) -> list[str]:
    rendered = []
    if values:
        for item in values:
            rendered.append(f"# {prefix}: {item}")
    else:
        rendered.append(f"# {prefix}: (empty)")
    return rendered


def _render_profile(
    template: str,
    workspace_root: Path,
    browser_allowlist: list[str],
    web_allowlist: list[str],
    require_approval: bool,
) -> str:
    browser_lines = _render_comment_lines(browser_allowlist, "browser-allowlist-domain")
    web_lines = _render_comment_lines(web_allowlist, "web-allowlist-domain")
    approval_lines = [
        f"# destructive-action-approval-required: {'true' if require_approval else 'false'}",
    ]

    rendered = template.replace("__WORKSPACE_ROOT__", str(workspace_root))
    rendered = rendered.replace("__BROWSER_ALLOWLIST__", "\n  ".join(browser_lines))
    rendered = rendered.replace("__WEB_ALLOWLIST__", "\n  ".join(web_lines))
    rendered = rendered.replace("__DESTRUCTIVE_ACTION_SIGNAL__", "\n  ".join(approval_lines))
    return rendered


def _run_parser_action(parser_path: str, flag: str, profile_path: Path) -> tuple[bool, str]:
    if not parser_path:
        return False, "apparmor parser unavailable"
    try:
        proc = subprocess.run(
            [parser_path, flag, str(profile_path)],
            capture_output=True,
            text=True,
            timeout=20,
        )
        if proc.returncode == 0:
            return True, "profile operation succeeded"
        return False, (proc.stderr or proc.stdout or "profile operation failed").strip()
    except Exception as exc:
        return False, f"profile operation failed: {exc}"


def _lifecycle_summary(
    *,
    workspace_root_changed: bool,
    reload_attempted: bool,
    reload_ok: bool,
    disable_attempted: bool,
    disable_ok: bool,
) -> dict:
    drift_state = "drifted" if workspace_root_changed else "in_sync"
    reload_state = "not_required"
    if workspace_root_changed:
        reload_state = "recommended"
    if reload_attempted:
        reload_state = "applied" if reload_ok else "failed"

    disable_state = "inactive"
    if disable_attempted:
        disable_state = "applied" if disable_ok else "failed"

    bridge_state = "rendered"
    if disable_attempted:
        bridge_state = "disabled" if disable_ok else "disable_failed"
    elif reload_attempted:
        bridge_state = "reloaded" if reload_ok else "reload_failed"
    elif workspace_root_changed:
        bridge_state = "rendered_with_drift"

    return {
        "bridge_state": bridge_state,
        "drift_state": drift_state,
        "reload_state": reload_state,
        "disable_state": disable_state,
        "operator_state": "attention_required" if workspace_root_changed or reload_state == "failed" or disable_state == "failed" else "ready",
    }


def _emit_operator_control(
    workspace_dir: Path,
    *,
    action: str,
    state: str,
    reason: str,
    object_payload: dict,
    metadata: dict | None = None,
) -> None:
    if str(os.environ.get("AGENTOS_BROKER_BYPASS", "0")).strip().lower() in {"1", "true", "yes", "on"}:
        return
    normalized_state = state
    normalized_reason = reason
    if str(os.environ.get("AGENTOS_BROKER_OVERRIDE", "0")).strip().lower() in {"1", "true", "yes", "on"}:
        normalized_state = "override"
        normalized_reason = f"operator override active: {action}"
    append_broker_transition(
        workspace_dir,
        kind="operator_control",
        action=action,
        state=normalized_state,
        reason=normalized_reason,
        actor={"component": "kernel_policy_bridge.py"},
        object=object_payload,
        correlation={"workspace": str(workspace_dir)},
        metadata=metadata or {},
    )


def build_bridge(
    workspace: str,
    output_dir: str,
    reload_profile: bool = False,
    disable_profile: bool = False,
    parser_cmd: str = "apparmor_parser",
) -> dict:
    wm = WorkspaceManager(workspace)
    workspace_root = _resolve_workspace_root(wm)
    browser_allowlist = list(getattr(wm, "browser_allowlist", []))
    web_allowlist = list(getattr(wm, "web_allowlist", []))
    network_allowlist = sorted({*browser_allowlist, *web_allowlist})
    require_approval = bool(getattr(wm, "require_approval", True))

    out_dir = Path(output_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    template_path = out_dir / "agentos-kernel-policy.profile.tmpl"
    profile_path = out_dir / "agentos-kernel-policy.profile"
    state_path = out_dir / "bridge-state.json"
    lifecycle_path = out_dir / "profile-lifecycle.json"

    template_text = _template_text()
    rendered = _render_profile(
        template_text,
        workspace_root,
        browser_allowlist=browser_allowlist,
        web_allowlist=web_allowlist,
        require_approval=require_approval,
    )

    prev_state = {}
    if state_path.exists():
        try:
            prev_state = json.loads(state_path.read_text(encoding="utf-8"))
        except Exception:
            prev_state = {}

    prev_workspace_root = str(prev_state.get("workspace_root", ""))
    current_workspace_root = str(workspace_root)
    workspace_root_changed = bool(prev_workspace_root and prev_workspace_root != current_workspace_root)

    template_path.write_text(template_text, encoding="utf-8")
    profile_path.write_text(rendered, encoding="utf-8")
    state_path.write_text(
        json.dumps(
            {
                "workspace_root": current_workspace_root,
                "browser_allowlist": browser_allowlist,
                "web_allowlist": web_allowlist,
                "network_allowlist": network_allowlist,
                "destructive_action_approval_required": require_approval,
            },
            ensure_ascii=True,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    parser_path = shutil.which(parser_cmd) or ""
    reload_attempted = False
    reload_ok = False
    reload_detail = ""
    disable_attempted = False
    disable_ok = False
    disable_detail = ""

    if reload_profile:
        reload_attempted = True
        if not parser_path:
            reload_detail = f"{parser_cmd} not found; cannot reload profile."
        else:
            reload_ok, reload_detail = _run_parser_action(parser_path, "-r", profile_path)

    if disable_profile:
        disable_attempted = True
        if not profile_path.exists():
            disable_detail = "profile file missing; nothing to disable"
            disable_ok = True
        elif not parser_path:
            disable_detail = f"{parser_cmd} not found; cannot disable profile."
        else:
            disable_ok, disable_detail = _run_parser_action(parser_path, "-R", profile_path)

    lifecycle_summary = _lifecycle_summary(
        workspace_root_changed=workspace_root_changed,
        reload_attempted=reload_attempted,
        reload_ok=reload_ok,
        disable_attempted=disable_attempted,
        disable_ok=disable_ok,
    )

    lifecycle_state = {
        "parser_cmd": parser_cmd,
        "parser_path": parser_path,
        "profile_path": str(profile_path),
        "template_path": str(template_path),
        "state_path": str(state_path),
        "rendered": True,
        "reload_attempted": reload_attempted,
        "reload_ok": reload_ok,
        "reload_detail": reload_detail,
        "disable_attempted": disable_attempted,
        "disable_ok": disable_ok,
        "disable_detail": disable_detail,
        "last_action": "disable" if disable_attempted else ("reload" if reload_attempted else "render"),
        **lifecycle_summary,
    }
    lifecycle_path.write_text(json.dumps(lifecycle_state, ensure_ascii=True, indent=2) + "\n", encoding="utf-8")

    broker_object = {
        "profile_path": str(profile_path),
        "workspace_root": current_workspace_root,
        "workspace_root_changed": str(workspace_root_changed).lower(),
        "parser_cmd": parser_cmd,
    }
    if reload_attempted:
        _emit_operator_control(
            wm.workspace_dir,
            action="policy_bridge_reload",
            state="allowed" if reload_ok else "blocked",
            reason=reload_detail or ("profile reload succeeded" if reload_ok else "profile reload failed"),
            object_payload=broker_object,
            metadata={"bridge_state": lifecycle_summary.get("bridge_state", "")},
        )
    if disable_attempted:
        _emit_operator_control(
            wm.workspace_dir,
            action="policy_bridge_disable",
            state="allowed" if disable_ok else "blocked",
            reason=disable_detail or ("profile disable succeeded" if disable_ok else "profile disable failed"),
            object_payload=broker_object,
            metadata={"bridge_state": lifecycle_summary.get("bridge_state", "")},
        )

    return {
        "ok": True,
        "exit_code": 0,
        "workspace": str(wm.workspace_dir),
        "workspace_root": current_workspace_root,
        "workspace_root_changed": workspace_root_changed,
        "browser_allowlist": browser_allowlist,
        "web_allowlist": web_allowlist,
        "network_allowlist": network_allowlist,
        "destructive_action_approval_required": require_approval,
        "template_path": str(template_path),
        "profile_path": str(profile_path),
        "state_path": str(state_path),
        "lifecycle_path": str(lifecycle_path),
        "reload_recommended": workspace_root_changed,
        "reload_attempted": reload_attempted,
        "reload_ok": reload_ok,
        "reload_detail": reload_detail,
        "disable_attempted": disable_attempted,
        "disable_ok": disable_ok,
        "disable_detail": disable_detail,
        "lifecycle": lifecycle_state,
        "lifecycle_summary": lifecycle_summary,
        "mechanism": "apparmor",
        "mode": "shadow_or_passive",
    }


def main() -> int:
    parser = argparse.ArgumentParser(description="Render AgentOS kernel policy bridge artifacts")
    parser.add_argument("--workspace", default="./workspaces/default")
    parser.add_argument("--output-dir", default="")
    parser.add_argument("--reload", action="store_true", help="Attempt apparmor_parser -r reload")
    parser.add_argument("--disable", action="store_true", help="Attempt apparmor_parser -R disable")
    parser.add_argument("--parser-cmd", default="apparmor_parser")
    parser.add_argument("--json", action="store_true")
    args = parser.parse_args()

    output_dir = args.output_dir.strip()
    if not output_dir:
        output_dir = str((Path(args.workspace).resolve() / "artifacts" / "kernel-policy"))

    report = build_bridge(
        workspace=args.workspace,
        output_dir=output_dir,
        reload_profile=args.reload,
        disable_profile=args.disable,
        parser_cmd=args.parser_cmd,
    )

    if args.json:
        print(json.dumps(report, ensure_ascii=True))
    else:
        print("AgentOS Kernel Policy Bridge")
        print("==========================")
        print(f"Workspace: {report['workspace']}")
        print(f"Workspace root: {report['workspace_root']}")
        print(f"Workspace root changed: {'yes' if report['workspace_root_changed'] else 'no'}")
        print(f"Mechanism: {report['mechanism']} ({report['mode']})")
        print(f"Template: {report['template_path']}")
        print(f"Profile: {report['profile_path']}")
        print(f"State: {report['state_path']}")
        print(f"Bridge lifecycle: {report['lifecycle_summary']['bridge_state']}")
        print(f"Drift state: {report['lifecycle_summary']['drift_state']}")
        print(
            "Reload recommended: "
            + ("yes (workspace root changed)" if report["reload_recommended"] else "no")
        )
        print(f"Reload state: {report['lifecycle_summary']['reload_state']}")
        if report["reload_attempted"]:
            print(f"Reload attempted: {'yes' if report['reload_ok'] else 'no'}")
            if report["reload_detail"]:
                print(f"Reload detail: {report['reload_detail']}")
        print(f"Disable state: {report['lifecycle_summary']['disable_state']}")
        if report["disable_attempted"]:
            print(f"Disable attempted: {'yes' if report['disable_ok'] else 'no'}")
            if report["disable_detail"]:
                print(f"Disable detail: {report['disable_detail']}")
    return int(report["exit_code"])


if __name__ == "__main__":
    raise SystemExit(main())
