'use strict';

function normalizeEndpoint(value){return String(value||'').trim().replace(/\/+$/,'');}
function modelDraftFingerprint(draft){return JSON.stringify([draft.provider,normalizeEndpoint(draft.endpoint),draft.model,draft.credential_revision]);}
function createModelDraftGuard(){
 let revision=0,verified='',verifiedProof='',sequence=0;
 const fingerprint=draft=>modelDraftFingerprint({...draft,credential_revision:revision});
 return {revision:()=>revision,invalidate(){revision++;verified='';verifiedProof='';sequence++;},canApply:draft=>verified===fingerprint(draft)&&verifiedProof.length>=32,async test(draft,request,currentDraft){const proof=fingerprint(draft),run=++sequence;let result;try{result=await request(draft);}catch(error){if(run===sequence){verified='';verifiedProof='';}throw error;}if(run!==sequence||proof!==fingerprint(currentDraft()))return {accepted:false,stale:true,result};if(!result?.ok||typeof result.test_proof!=='string'||result.test_proof.length<32){verified='';verifiedProof='';return {accepted:false,stale:false,result};}verified=proof;verifiedProof=result.test_proof;return {accepted:true,stale:false,result};},async apply(draft,save){if(!this.canApply(draft))return false;const payload={...draft,test_proof:verifiedProof};delete payload.credential_revision;await save(payload);this.invalidate();return true;}};
}
function isDiagnosticTask(task){return /^\s*\/(?:start|help)(?:\s|$)/i.test(task?.title||'')||String(task?.request_key||'').startsWith('telegram-verify:');}
function statusText(task){if(task.status_kind==='active')return '진행 중';if(task.status==='cancelled')return '취소됨';if(task.status==='partial')return '일부 완료';if(task.status==='failed')return '실패';if(task.status==='interrupted')return '중단됨';if(task.delivery==='unknown')return '전달 여부 알 수 없음';if(task.status_kind==='finished')return '완료';return '확인 필요';}
function taskOutcome(task){if(task.waits?.length)return {title:'필요한 행동',text:task.waits.join(' · '),kind:'attention'};if(task.status==='cancelled')return {title:'취소됨',text:task.error||'이 작업은 취소되어 더 이상 실행되지 않습니다.',kind:'attention'};if(task.status==='failed'||task.status==='interrupted')return {title:'완료하지 못함',text:task.error||'마지막으로 관찰된 상태를 확인해 주세요.',kind:'attention'};if(task.delivery==='unknown'&&task.status_kind!=='active')return {title:'전달 여부 알 수 없음',text:task.response||'Telegram 전달 여부를 확인할 수 없습니다. 자동으로 다시 실행하지 않습니다.',kind:'attention'};if(task.response&&['succeeded','partial'].includes(task.status)){const text=task.status==='partial'&&task.error?`${task.response}\n\n완료하지 못한 부분: ${task.error}`:task.response;return {title:task.status==='partial'?'일부 결과':'결과',text,kind:task.status==='partial'?'attention':''};}if(task.status_kind==='active')return {title:'진행 중',text:'새 이벤트를 기다리고 있습니다.',kind:''};return {title:'결과 정보 없음',text:'완료 상태는 관찰됐지만 읽을 수 있는 결과가 제공되지 않았습니다.',kind:'attention'};}
function requestSource(task){return String(task?.channel||'').startsWith('telegram:')?'Telegram':task?.channel?'로컬 또는 연결된 채널':'요청 경로 알 수 없음';}
function workspaceSaveCandidates(jobs,workspaceId,savedJobIds){const saved=new Set(savedJobIds||[]);return (jobs||[]).filter(job=>['succeeded','partial'].includes(job.status)&&(!job.workspace_id||job.workspace_id===workspaceId)&&!saved.has(job.id));}
function modelPresetDraft(preset){return {provider:preset.provider,endpoint:normalizeEndpoint(preset.endpoint),model:String(preset.model||'').trim(),api_key:''};}
function capabilityActions(capability){if(!['google-drive-read','compatibility-a2a-peer','google-calendar-create','builtin-mcp-read'].includes(capability?.id))return [];if(capability.state==='enabled')return ['pause','disconnect'];if(capability.state==='paused')return ['resume'];return [];}
function clearMobileDetailWhenEmpty(detail,rows){if(!rows.length)detail.classList.remove('mobile-detail');return !rows.length;}
function contextSharingWarning(inbox){return inbox?.sharing_requires_policy_and_per_request_approval?'이 정책을 허용해도 각 Telegram 작업마다 공유 승인이 필요합니다.':'';}
function settingsFeedbackId(area){return area==='subscription'?'subscription-feedback':'model-feedback';}
function rememberTaskDisclosures(store,taskId,technical){if(!taskId||!technical)return;store.set(taskId,{technical:!!technical.open,original:!!technical.querySelector?.('details')?.open});}
function restoreTaskDisclosures(store,taskId,technical,original){const state=store.get(taskId)||{};technical.open=!!state.technical;if(original)original.open=!!state.original;return state;}
function isOpenRouterCompletion(event,origin){return event?.origin===origin&&event?.data?.type==='agentos-openrouter-connected';}
function parseOpenRouterFlow(raw,now=Date.now()){
 try{
  const flow=JSON.parse(raw||'null');
  if(!flow||typeof flow.verifier!=='string'||!/^[A-Za-z0-9_-]{43,128}$/.test(flow.verifier)||typeof flow.state!=='string'||!/^[0-9a-f-]{36}$/i.test(flow.state)||!Number.isFinite(flow.expires)||flow.expires<=now||typeof flow.url!=='string')return null;
  const url=new URL(flow.url);if(url.origin!=='https://openrouter.ai'||url.pathname!=='/auth')return null;
  return flow;
 }catch(_error){return null;}
}
function shouldRenderWorkspaceDetail(selectedId,requestedId,requestSequence,currentSequence){return selectedId===requestedId&&requestSequence===currentSequence;}
function shouldInvalidateWorkspaceDetailForDeletion(item,selectedId){return item?.deleteKind==='results'&&!!item.workspace_id&&item.workspace_id===selectedId;}
function workspaceResultSummary(workspace){const count=Number.isInteger(workspace?.result_count)?workspace.result_count:(workspace?.results||[]).length;return {count,label:`${count}개 완료 결과`};}
function shouldRefreshSelectedTask(previous,current){if(!current)return false;if(!previous?.events)return true;return previous.events_count!==current.events_count||previous.observed_at!==current.observed_at||previous.status!==current.status;}
function refreshSelectedTaskDetail(previous,current,load){return shouldRefreshSelectedTask(previous,current)?load(current.id):Promise.resolve(null);}
function mergeTaskProgress(summary,previous,jobs){
 const old=new Map((previous?.tasks||[]).map(task=>[task.id,task]));
 const state=new Map((jobs||[]).map(job=>[job.id,job]));
 return {...summary,tasks:(summary?.tasks||[]).map(task=>{
  const detail=old.get(task.id)||{},job=state.get(task.id)||{};
  const terminal=['succeeded','partial'].includes(task.status),failed=['failed','interrupted','partial'].includes(task.status);
  return {...detail,...task,response:terminal?(task.response??job.response??detail.response):undefined,error:failed?(task.error??job.error??detail.error):undefined,request:job.message??detail.request,channel:job.channel??detail.channel,delivery:job.delivery??detail.delivery,request_key:job.request_key??detail.request_key};
 })};
}
function recordItems(space){
 if(Array.isArray(space?.items))return space.items.map(item=>({...item}));
 const rows=[];
 for(const item of space?.memories||[])rows.push({...item,type:item.memory_key?'memory':item.record_kind==='note'?'note':'saved',label:item.memory_key?'기억':item.record_kind==='note'?'메모':'메모 · 기억 (유형 미제공)',deleteKind:'memories'});
 for(const item of space?.context||[])rows.push({...item,type:'temporary',label:'임시 자료',content:`${item.source_kind||'자료'} · ${item.source_app||'로컬'} · ${item.sharing_state||'공유 안 함'}`});
 for(const item of space?.results||[])rows.push({...item,type:'artifact',label:'저장된 결과',deleteKind:'results'});
 return rows.sort((a,b)=>(b.created||b.captured_at||0)-(a.created||a.captured_at||0));
}
function filterLocalRecords(space,query='',filter='all'){const needle=String(query).trim().toLocaleLowerCase();return recordItems(space).filter(item=>(filter==='all'||item.type===filter||(filter==='saved'&&['note','memory'].includes(item.type)))&&(!needle||(`${item.label} ${item.memory_key||''} ${item.content||''} ${item.source_kind||''}`).toLocaleLowerCase().includes(needle)));}
function recordPageMatches(records,query,filter){return Boolean(records&&records.query===String(query).trim()&&records.filter===filter);}
// A MemoryCandidate decision writes canonical Memory, so every request body
// below is built from `review.inspected` - the candidate row the owner read
// back - and never from the list page or from the approval the server issued.
// `approval.source_digest` is compared to, not copied from, the inspected
// digest: an approval issued against another candidate or other content
// cannot be spent on what is on screen.
function memoryCandidateApprovalMatches(review){const inspected=review&&review.inspected,approval=review&&review.approval;return Boolean(inspected&&approval&&approval.approval_token&&approval.subject_id===inspected.id&&approval.source_digest===inspected.content_digest);}
// Approval stays two owner steps. No state both issues and spends an
// approval: 'accept' is reachable only once an approval already matches the
// inspected candidate, which only 'request-approval' can produce.
function memoryCandidateStep(review,candidateId){if(!review||!review.inspected||review.inspected.id!==candidateId)return 'inspect';return memoryCandidateApprovalMatches(review)?'accept':'request-approval';}
function memoryCandidateDecisionBody(review,operation){const inspected=review&&review.inspected;if(!inspected||!inspected.id||!inspected.work_ref||!inspected.content_digest)return null;const body={operation,id:inspected.id,work_ref:inspected.work_ref,content_digest:inspected.content_digest};if(operation!=='accept')return body;if(!memoryCandidateApprovalMatches(review))return null;body.approval_token=review.approval.approval_token;return body;}
// React to a pending count that changed, never to one that merely differs
// from the loaded page, so an open section cannot poll itself in a loop.
function memoryCandidateReloadNeeded(open,pendingCount,observedCount){return Boolean(open)&&pendingCount!==observedCount;}
if(typeof module!=='undefined'&&module.exports)module.exports={normalizeEndpoint,modelDraftFingerprint,createModelDraftGuard,isDiagnosticTask,statusText,taskOutcome,requestSource,workspaceSaveCandidates,modelPresetDraft,capabilityActions,clearMobileDetailWhenEmpty,contextSharingWarning,settingsFeedbackId,rememberTaskDisclosures,restoreTaskDisclosures,isOpenRouterCompletion,parseOpenRouterFlow,shouldRenderWorkspaceDetail,shouldInvalidateWorkspaceDetailForDeletion,workspaceResultSummary,shouldRefreshSelectedTask,refreshSelectedTaskDetail,mergeTaskProgress,recordItems,filterLocalRecords,recordPageMatches,memoryCandidateApprovalMatches,memoryCandidateStep,memoryCandidateDecisionBody,memoryCandidateReloadNeeded};

if(typeof document!=='undefined'){
const $=id=>document.getElementById(id);
const providers={ollama:{endpoint:'http://127.0.0.1:11434',help:'실행 중인 Ollama 주소입니다.'},compatible:{endpoint:'https://openrouter.ai/api/v1',help:'OpenAI 호환 API 주소입니다.',model:'openrouter/free'},openai:{endpoint:'https://api.openai.com/v1',help:'OpenAI Developer API 주소입니다.',model:'gpt-4o-mini'},anthropic:{endpoint:'https://api.anthropic.com',help:'Anthropic API 주소입니다.'}};
const providerNames={compatible:'호환 API',openai:'OpenAI',ollama:'Ollama',anthropic:'Anthropic'};
function displayProvider(model){return model.provider==='compatible'&&normalizeEndpoint(model.endpoint)==='https://api.openai.com/v1'?'openai':model.provider;}
let claimed=false,authenticated=false,refreshing=false,refreshQueued=false,modelLoaded=false,rootsLoaded=false,fileWorkspaceLoaded=false,modelLoadRevision=0,rootsLoadRevision=0,fileWorkspaceLoadRevision=0,activeModelDestination='';
const modelGuard=createModelDraftGuard();
let activeView='tasks',activeSettings='ai',selectedTaskId='',selectedRecordKey='',selectedWorkspaceId='',taskProgress=null,lastHome=null,lastState=null,lastSpace=null,lastRecords=null,taskRenderFingerprint='',recordRenderFingerprint='',taskDetailSequence=0,workspaceDetailSequence=0,recordLoadSequence=0;
const taskDetailInflight=new Map();
let recordRefreshPromise=null;
let memoryCandidateRows=null,selectedCandidateId='',memoryCandidateReview=null,memoryCandidateFingerprint='',memoryCandidateLoadSequence=0,memoryCandidateObservedCount=null;
const workspaceResultSummaries=new Map();
const expandedTaskEvents=new Set();
const taskDisclosureState=new Map();
let contextDraftDirty=false,telegramDraftOpen=false,recordDeletePending='';
let bootstrap=new URLSearchParams(location.hash.slice(1)).get('setup')||'';
if(bootstrap)history.replaceState(null,'',location.pathname+location.search);

async function api(path,body,method){
 const response=await fetch(path,{method:method||(body===undefined?'GET':'POST'),headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});
 let data={};try{data=await response.json();}catch(_error){data={};}
 if(!response.ok)throw new Error(data.error||'요청을 처리할 수 없습니다.');
 return data;
}
function element(tag,text,className){const node=document.createElement(tag);if(text!==undefined)node.textContent=text;if(className)node.className=className;return node;}
function setError(id,value){$(id).textContent=value?.message||String(value||'');}
async function busy(button,fn){const label=button.textContent,wasDisabled=button.disabled;button.disabled=true;button.textContent='처리 중…';try{return await fn();}finally{button.textContent=label;button.disabled=wasDisabled;if(button.id==='apply-model')syncApplyState();}}
function safeTime(value){return value?new Date(value*1000).toLocaleString():'시간 정보 없음';}

function routeFromLocation(){const parts=location.hash.replace(/^#/,'').split('/');return {view:['tasks','records','settings'].includes(parts[0])?parts[0]:'tasks',settings:['ai','files','external','privacy'].includes(parts[1])?parts[1]:'ai'};}
function navigate(view,settings,{replace=false}={}){activeView=view;activeSettings=settings||activeSettings;const hash='#'+view+(view==='settings'?'/'+activeSettings:'');if(location.hash!==hash)history[replace?'replaceState':'pushState'](null,'',hash);renderNavigation();}
function renderNavigation(){document.querySelectorAll('[data-view-panel]').forEach(panel=>panel.hidden=panel.dataset.viewPanel!==activeView);document.querySelectorAll('[data-view]').forEach(button=>button.classList.toggle('active',button.dataset.view===activeView));document.querySelectorAll('[data-settings-panel]').forEach(panel=>panel.hidden=panel.dataset.settingsPanel!==activeSettings);document.querySelectorAll('[data-settings]').forEach(button=>button.classList.toggle('active',button.dataset.settings===activeSettings));}
function showRecords(){if(recordPageMatches(lastRecords,$('record-query').value,$('record-filter').value)){recordRenderFingerprint='';renderRecords();void refreshLoadedRecords();}else void loadRecords();}
document.querySelectorAll('[data-view]').forEach(button=>button.onclick=()=>{navigate(button.dataset.view);if(button.dataset.view==='records')showRecords();});
document.querySelectorAll('[data-settings]').forEach(button=>button.onclick=()=>navigate('settings',button.dataset.settings));
$('brand-home').onclick=event=>{event.preventDefault();navigate('tasks');};
window.addEventListener('popstate',()=>{const route=routeFromLocation();activeView=route.view;activeSettings=route.settings;renderNavigation();if(activeView==='records')showRecords();});

function modelDraft(){const endpoint=normalizeEndpoint($('endpoint').value);if(!activeModelDestination)activeModelDestination=[$('provider').value,endpoint].join('|');return {provider:$('provider').value,endpoint,model:$('model-name').value.trim(),api_key:$('api-key').value,require_key:activeModelDestination!==[$('provider').value,endpoint].join('|'),credential_revision:modelGuard.revision()};}
function syncApplyState(){$('apply-model').disabled=!modelGuard.canApply(modelDraft());}
function invalidateModelDraft(message){modelGuard.invalidate();syncApplyState();if(message)$('model-feedback').textContent=message;}
function invalidateModelLoad(){modelLoadRevision++;modelLoaded=false;}
function invalidateRootsLoad(){rootsLoadRevision++;rootsLoaded=false;}
function invalidateFileWorkspaceLoad(){fileWorkspaceLoadRevision++;fileWorkspaceLoaded=false;}
function applyModelPreset(preset,message){const draft=modelPresetDraft(preset);$('provider').value=draft.provider;$('endpoint').value=draft.endpoint;$('model-name').value=draft.model;$('api-key').value=draft.api_key;invalidateModelDraft(message);}
$('provider').onchange=()=>{const selected=providers[$('provider').value];$('endpoint').value=selected.endpoint;if(selected.model)$('model-name').value=selected.model;$('api-key').value='';$('endpoint-help').textContent=selected.help;invalidateModelDraft('연결 대상이 바뀌었습니다. 새 설정을 다시 테스트하세요.');};
['endpoint','model-name','api-key'].forEach(id=>$(id).addEventListener('input',()=>invalidateModelDraft('입력한 설정이 바뀌었습니다. 다시 테스트하세요.')));
$('test-model').onclick=()=>busy($('test-model'),async()=>{const draft=modelDraft();$('model-feedback').textContent='입력한 설정을 확인하고 있습니다…';try{const outcome=await modelGuard.test(draft,value=>api('/api/model/test',value),modelDraft);if(outcome.stale){$('model-feedback').textContent='입력이 바뀌어 이전 테스트 결과를 적용하지 않았습니다.';return;}if(!outcome.accepted)throw new Error(outcome.result?.error||'도구 호출을 확인하지 못했습니다.');$('model-feedback').textContent='현재 입력한 설정의 응답과 도구 호출을 확인했습니다.';}catch(error){setError('model-feedback',error);}finally{syncApplyState();}});
$('model-form').onsubmit=event=>{event.preventDefault();const draft=modelDraft();if(!modelGuard.canApply(draft)){$('model-feedback').textContent='먼저 현재 입력한 설정을 테스트하세요.';syncApplyState();return;}busy($('apply-model'),async()=>{try{await modelGuard.apply(draft,payload=>api('/api/model',payload));$('api-key').value='';invalidateModelLoad();$('model-feedback').textContent='테스트한 직접 API 설정을 저장했습니다. 추가 테스트는 실행하지 않았습니다.';await refresh();}catch(error){setError('model-feedback',error);}});};

function renderExecutionConnection(settings){
 const model=settings?.model||{},subscription=settings?.subscription_engines||{},selected=(subscription.engines||[]).find(item=>item.id===subscription.selected),box=$('active-ai');box.replaceChildren(element('strong','현재 요청 실행 연결'));
 const shownProvider=displayProvider(model);if(subscription.selected){box.append(element('p',`${selected?.name||'선택된 구독 CLI'} · 구독 CLI 우선`),element('p','웹·Telegram의 AI 요청 모두 이 선택을 우선 사용합니다. 직접 API 테스트는 실행 경로를 바꾸지 않습니다.'));box.append(element('p',selected?.installed===false?'선택한 CLI를 찾지 못했습니다. 직접 API로 자동 전환하지 않습니다.':selected?.connected?'로그인 확인됨 · 실제 응답 확인과는 다릅니다.':'로그인 확인 상태를 알 수 없습니다.'));box.append(element('p','모델 정보 미제공'));box.append(element('small',model.model?`저장된 직접 API: ${providerNames[shownProvider]||shownProvider} · ${model.model}`:'직접 API 미설정 · 구독 CLI 선택과 별개입니다.'));return;}
 if(model.model)box.append(element('p',`${providerNames[shownProvider]||shownProvider} · ${model.model} · 직접 API`),element('p',settings.model_ready?'저장된 설정 검증됨 · 실제 실행은 작업에서 확인':'저장된 설정 확인 필요'));else box.append(element('p','직접 API 미설정 · 구독 CLI도 선택되지 않았습니다.'));
}
function renderSubscriptionEngines(subscription){const box=$('subscription-engines'),fingerprint=JSON.stringify(subscription||{});if(box.dataset.state===fingerprint)return;box.dataset.state=fingerprint;box.replaceChildren(element('h3','구독 CLI'));const feedback=element('p',undefined,'error');feedback.id='subscription-feedback';feedback.setAttribute('role','status');box.append(feedback);for(const engine of subscription?.engines||[]){const current=engine.id===subscription.selected,row=element('div',undefined,'subscription-engine');row.append(element('strong',engine.name),element('p',current?'현재 선택됨 · 웹·Telegram 요청에 우선 사용':engine.installed?'설치 확인됨':'CLI를 찾지 못했습니다.'));if(engine.installed&&!current){const button=element('button',`${engine.name} 로그인 완료 · ${subscription.selected?'전환':'선택'}`);button.type='button';button.onclick=()=>busy(button,async()=>{try{await api('/api/subscription-engines/connect',{engine:engine.id,officially_authenticated:true});await refresh();}catch(error){setError('subscription-feedback',error);}});row.append(button);}box.append(row);}}

function openMobileDetail(node){if(matchMedia('(max-width: 620px)').matches)node.classList.add('mobile-detail');}
function mobileBack(node){const button=element('button','목록으로','mobile-back');button.type='button';button.onclick=()=>node.classList.remove('mobile-detail');return button;}
async function selectTask(id,openDetail=true){selectedTaskId=id;taskRenderFingerprint='';renderTasks();if(openDetail)openMobileDetail($('task-detail'));if(taskDetailInflight.has(id))return taskDetailInflight.get(id);const request=++taskDetailSequence,pending=api('/api/tasks/'+encodeURIComponent(id));taskDetailInflight.set(id,pending);try{const response=await pending;if(response.selected&&request===taskDetailSequence&&selectedTaskId===id){const summary={...(taskProgress||{}),tasks:(taskProgress?.tasks||[]).map(item=>item.id===id?{...item,...response.selected}:item)};taskProgress=mergeTaskProgress(summary,taskProgress,lastState?.jobs);taskRenderFingerprint='';renderTasks();if(openDetail)openMobileDetail($('task-detail'));}}catch(error){if(request===taskDetailSequence)setError('global-error',error);}finally{if(taskDetailInflight.get(id)===pending)taskDetailInflight.delete(id);}}
function renderTasks(){
 const list=$('task-list'),detail=$('task-detail'),tasks=(taskProgress?.tasks||[]).filter(task=>!isDiagnosticTask(task));
 if(!tasks.length){clearMobileDetailWhenEmpty(detail,tasks);if(selectedTaskId){selectedTaskId='';taskDetailSequence++;}if(taskRenderFingerprint==='empty')return;taskRenderFingerprint='empty';list.replaceChildren();list.append(element('p','표시할 일반 작업이 없습니다. 연결 확인 활동은 개인정보 · 진단에 남아 있습니다.','muted'));detail.replaceChildren(element('p','Telegram에서 요청한 작업이 여기에 표시됩니다.','empty-state'));detail.dataset.taskId='';return;}
 if(!selectedTaskId||!tasks.some(task=>task.id===selectedTaskId))selectedTaskId=tasks[0].id;
 const fingerprint=JSON.stringify([tasks,selectedTaskId]);if(taskRenderFingerprint===fingerprint)return;taskRenderFingerprint=fingerprint;list.replaceChildren();
 for(const task of tasks){const row=element('button',undefined,'item-row'+(task.id===selectedTaskId?' selected':''));row.type='button';row.append(element('strong',task.title),element('span',`${statusText(task)} · ${safeTime(task.started_at)}`));row.onclick=()=>selectTask(task.id);list.append(row);}
 const task=tasks.find(item=>item.id===selectedTaskId);if(!task)return;rememberTaskDisclosures(taskDisclosureState,detail.dataset.taskId,detail.querySelector('.technical'));for(const open of detail.querySelectorAll('.task-event[open]'))expandedTaskEvents.add(open.dataset.eventId);detail.replaceChildren(mobileBack(detail),element('h2',task.title),element('p',`${statusText(task)} · ${safeTime(task.observed_at||task.started_at)}`,'muted'));detail.dataset.taskId=task.id;
 const outcome=taskOutcome(task),result=element('section',undefined,'outcome '+outcome.kind);result.append(element('h3',outcome.title),element('p',outcome.text));detail.append(result);
 if(task.artifacts?.length){const artifacts=element('section');artifacts.append(element('h3','결과물'));for(const artifact of task.artifacts){const row=element('div',undefined,'record-row');row.append(element('p',`${artifact.kind} · ${artifact.path||'프로젝트에 저장됨'} · ${artifact.state||'current'}`));if(artifact.path&&navigator.clipboard){const copy=element('button','파일 위치 복사');copy.type='button';copy.onclick=()=>navigator.clipboard.writeText(artifact.path).then(()=>copy.textContent='복사됨');row.append(copy);}else if(artifact.workspace_id){const open=element('button','프로젝트 보기');open.type='button';open.onclick=()=>{navigate('records');$('projects').open=true;selectWorkspace(artifact.workspace_id);};row.append(open);}artifacts.append(row);}detail.append(artifacts);}
 const timeline=element('section',undefined,'timeline');timeline.append(element('h3','관찰된 과정'));if(!task.events?.length)timeline.append(element('p',taskProgress?.unknown_detail_message||'관찰된 실행 이벤트가 없습니다.','muted'));for(const event of task.events||[]){const item=element('details',undefined,'task-event');item.dataset.eventId=String(event.id);item.open=expandedTaskEvents.has(item.dataset.eventId);item.ontoggle=()=>item.open?expandedTaskEvents.add(item.dataset.eventId):expandedTaskEvents.delete(item.dataset.eventId);item.append(element('summary',`${event.tool} · ${event.status==='succeeded'?'완료':event.status==='failed'?'실패':event.status==='running'?'실행 중':'관찰됨'} · ${safeTime(event.created)}`),element('p',event.summary));const entries=Object.entries(event.details||{});if(entries.length)item.append(element('p',entries.map(([key,value])=>`${key}: ${value}`).join(' · '),'technical'));timeline.append(item);}detail.append(timeline);
 const technical=element('details',undefined,'technical');technical.append(element('summary','실행 상세'),element('p',`요청 ID ${task.id} · 요청 경로 ${requestSource(task)} · 설정 ${task.configured?.runtime||'알 수 없음'} / 관찰 ${task.observed?.runtime||'알 수 없음'}`));let original;if(task.request){original=element('details');original.append(element('summary','원래 요청 보기'),element('p',task.request));technical.append(original);}restoreTaskDisclosures(taskDisclosureState,task.id,technical,original);if(task.source_references?.length)technical.append(element('p','사용한 근거: '+task.source_references.join(' · ')));detail.append(technical);
}

function recordKey(item){return `${item.type}:${item.id}`;}
function filteredRecords(){return lastRecords?recordItems(lastRecords):filterLocalRecords(lastSpace,$('record-query').value,$('record-filter').value);}
async function loadRecords({append=false,refreshLoaded=false,throwOnError=false}={}){const query=$('record-query').value.trim(),filter=$('record-filter').value,request=++recordLoadSequence,start=append?(lastRecords?.items?.length||0):0,target=refreshLoaded?Math.max(100,lastRecords?.items?.length||0):start+100;try{let offset=start,records=null,items=[];do{const page=await api('/api/personal-records?'+new URLSearchParams({query,filter,limit:'100',offset:String(offset)}));if(request!==recordLoadSequence||query!==$('record-query').value.trim()||filter!==$('record-filter').value)return false;records=page;items.push(...page.items);offset+=page.items.length;if(!page.has_more||!page.items.length||offset>=target)break;}while(true);records.query=query;records.filter=filter;records.items=append&&lastRecords?[...lastRecords.items,...items]:items;lastRecords=records;recordRenderFingerprint='';renderRecords();$('record-search-feedback').textContent=query?`로컬 원문 기록 ${records.match_count}개를 찾았습니다.`:'';return true;}catch(error){if(request===recordLoadSequence)setError('record-search-feedback',error);if(throwOnError)throw error;return false;}}
function refreshLoadedRecords(){if(recordRefreshPromise)return recordRefreshPromise;recordRefreshPromise=loadRecords({refreshLoaded:true}).finally(()=>{recordRefreshPromise=null;});return recordRefreshPromise;}
function renderRecordCounts(){const counts=lastRecords?.counts||{saved:0,note:0,memory:0,temporary:0,artifact:0};if(!lastRecords)recordItems(lastSpace).forEach(row=>counts[row.type]=(counts[row.type]||0)+1);const box=$('record-counts');box.replaceChildren();if(counts.saved)box.append(element('span',`메모 · 기억 ${counts.saved}개 · 유형 미제공`,'count-chip'));[['메모','note'],['기억','memory'],['임시 자료','temporary'],['저장된 결과','artifact']].forEach(([label,key])=>box.append(element('span',`${label} ${counts[key]||0}개`,'count-chip')));}
function renderRecords(){
 const list=$('record-list'),detail=$('record-detail'),rows=filteredRecords();
 if(!rows.length){clearMobileDetailWhenEmpty(detail,rows);const fingerprint=JSON.stringify(['empty',$('record-query').value,$('record-filter').value,recordDeletePending]);if(recordRenderFingerprint===fingerprint)return;recordRenderFingerprint=fingerprint;renderRecordCounts();list.replaceChildren();list.append(element('p','조건에 맞는 저장 기록이 없습니다. 대화 이력과 저장한 기록은 구분됩니다.','muted'));detail.replaceChildren(element('p','기록을 선택하면 세부 내용을 확인할 수 있습니다.','empty-state'));return;}
 if(!selectedRecordKey||!rows.some(item=>recordKey(item)===selectedRecordKey))selectedRecordKey=recordKey(rows[0]);
 const fingerprint=JSON.stringify([rows,selectedRecordKey,recordDeletePending,$('record-query').value,$('record-filter').value]);if(recordRenderFingerprint===fingerprint)return;recordRenderFingerprint=fingerprint;renderRecordCounts();list.replaceChildren();
 for(const item of rows){const key=recordKey(item),button=element('button',undefined,'item-row'+(key===selectedRecordKey?' selected':''));button.type='button';button.append(element('strong',item.memory_key||item.content||item.label),element('span',`${item.label} · ${safeTime(item.created||item.captured_at)}`));button.onclick=()=>{selectedRecordKey=key;recordRenderFingerprint='';renderRecords();openMobileDetail(detail);};list.append(button);}
 if(lastRecords?.has_more){const more=element('button','더 보기','item-row');more.type='button';more.onclick=()=>busy(more,()=>loadRecords({append:true}));list.append(more);}
 const item=rows.find(row=>recordKey(row)===selectedRecordKey);detail.replaceChildren(mobileBack(detail),element('p',item.label,'eyebrow'),element('h2',item.memory_key||item.label),element('p',item.content||'내용 원문은 이 화면에 보관되지 않습니다.'));
 if(item.type==='artifact')detail.append(element('p',`프로젝트 ${item.workspace_id||'미지정'} · 작업 ${item.job_id||'미지정'}`,'muted'));if(item.type==='temporary')detail.append(element('p',`만료 ${safeTime(item.expires_at)} · ${item.sharing_state||'공유 상태 알 수 없음'}`,'muted'));
 if(item.deleteKind){const actions=element('div',undefined,'record-actions');const remove=element('button',recordDeletePending===selectedRecordKey?'삭제 확인':'삭제');remove.type='button';remove.onclick=async()=>{if(recordDeletePending!==selectedRecordKey){recordDeletePending=selectedRecordKey;recordRenderFingerprint='';renderRecords();return;}recordLoadSequence++;if(shouldInvalidateWorkspaceDetailForDeletion(item,selectedWorkspaceId))workspaceDetailSequence++;try{const deleted=await api('/api/personal-space/'+item.deleteKind+'/'+encodeURIComponent(item.id),undefined,'DELETE');recordDeletePending='';selectedRecordKey='';if(lastRecords){lastRecords.items=lastRecords.items.filter(row=>recordKey(row)!==recordKey(item));lastRecords.match_count=Math.max(0,(lastRecords.match_count||0)-1);if(lastRecords.counts&&lastRecords.counts[item.type]>0)lastRecords.counts[item.type]--;recordRenderFingerprint='';renderRecords();}await loadRecords({refreshLoaded:true,throwOnError:true});if(deleted.workspace_id){workspaceResultSummaries.delete(deleted.workspace_id);lastHome=await api('/api/home');renderWorkspaces(lastHome,lastState);await loadWorkspaceResultSummaries(lastHome.workspaces);if(selectedWorkspaceId===deleted.workspace_id)await selectWorkspace(deleted.workspace_id);}}catch(error){setError('record-search-feedback',error);}};actions.append(remove);detail.append(actions);}
}
$('record-search').onsubmit=event=>{event.preventDefault();void loadRecords();};
$('record-query').oninput=()=>{$('record-search-feedback').textContent='';void loadRecords();};
$('record-filter').onchange=()=>{recordDeletePending='';void loadRecords();};

// Pending MemoryCandidates. `/api/personal-space` already carries the pending
// count and content, but not the `work_ref` or `content_digest` a decision
// needs, so the count keeps the section discoverable on the existing refresh
// and the actionable rows come from the dedicated owner endpoint.
async function loadMemoryCandidates(){
 const request=++memoryCandidateLoadSequence;
 try{const data=await api('/api/personal-space/memory-candidates');if(request!==memoryCandidateLoadSequence)return;memoryCandidateRows=data.candidates||[];memoryCandidateFingerprint='';renderMemoryCandidates();}catch(error){if(request===memoryCandidateLoadSequence)setError('memory-candidate-feedback',error);}
}
function renderMemoryCandidateSummary(space){
 const count=space?.memory_candidate_count||0;
 $('memory-candidate-summary').textContent=count?`검토 대기 ${count}개`:'검토 대기 없음';
 if(memoryCandidateReloadNeeded($('memory-candidates').open,count,memoryCandidateObservedCount)){memoryCandidateObservedCount=count;void loadMemoryCandidates();}
}
function renderMemoryCandidates(){
 const list=$('memory-candidate-list'),detail=$('memory-candidate-detail'),rows=memoryCandidateRows||[];
 if(selectedCandidateId&&!rows.some(row=>row.id===selectedCandidateId)){selectedCandidateId='';memoryCandidateReview=null;}
 const fingerprint=JSON.stringify([rows,selectedCandidateId,memoryCandidateReview]);if(memoryCandidateFingerprint===fingerprint)return;memoryCandidateFingerprint=fingerprint;
 list.replaceChildren();
 for(const row of rows){const button=element('button',undefined,'item-row'+(row.id===selectedCandidateId?' selected':''));button.type='button';button.append(element('strong',row.memory_key||'기억 키 없음'),element('span',`저장 전 후보 · ${safeTime(row.created)}`));button.onclick=()=>{selectedCandidateId=row.id;memoryCandidateReview=null;memoryCandidateFingerprint='';renderMemoryCandidates();};list.append(button);}
 if(!rows.length)list.append(element('p','검토를 기다리는 기억 후보가 없습니다.','muted'));
 const selected=rows.find(row=>row.id===selectedCandidateId);
 if(!selected)return detail.replaceChildren(element('p','후보를 선택하면 저장 전 내용을 확인할 수 있습니다.','empty-state'));
 detail.replaceChildren(element('p','저장 전 기억 후보','eyebrow'),element('h4',selected.memory_key||'기억 키 없음'),element('p',`제안 시각 ${safeTime(selected.created)}`,'muted'));
 const step=memoryCandidateStep(memoryCandidateReview,selected.id);
 if(step==='inspect'){
  detail.append(element('p','승인 전에는 기억으로 저장하지 않습니다. 검토를 눌러 이 후보의 현재 내용과 대조값을 확인하세요.','muted'));
  const inspect=element('button','검토');inspect.type='button';
  inspect.onclick=()=>busy(inspect,async()=>{try{const inspected=await api('/api/personal-space/memory-candidates/request',{operation:'inspect',id:selected.id,work_ref:selected.work_ref});memoryCandidateReview={inspected,approval:null};memoryCandidateFingerprint='';renderMemoryCandidates();$('memory-candidate-feedback').textContent='';}catch(error){setError('memory-candidate-feedback',error);}});
  return detail.append(inspect);
 }
 const inspected=memoryCandidateReview.inspected,actions=element('div',undefined,'button-row');
 detail.append(element('p',inspected.content||'내용이 제공되지 않았습니다.','outcome'),element('p',`검토한 내용 대조값 ${inspected.content_digest}`,'technical'));
 if(step==='request-approval'){
  const request=element('button','이 내용으로 승인 요청');request.type='button';
  request.onclick=()=>busy(request,async()=>{try{const approval=await api('/api/personal-space/memory-candidates/request',memoryCandidateDecisionBody(memoryCandidateReview,'request-approval'));memoryCandidateReview={inspected,approval};memoryCandidateFingerprint='';renderMemoryCandidates();$('memory-candidate-feedback').textContent='승인을 요청했습니다. 위 내용을 다시 확인한 뒤 승인을 확정하세요.';}catch(error){setError('memory-candidate-feedback',error);}});
  actions.append(request);
 }else{
  const accept=element('button','확인한 내용으로 승인 확정','primary');accept.type='button';
  accept.onclick=()=>busy(accept,async()=>{const body=memoryCandidateDecisionBody(memoryCandidateReview,'accept');if(!body)return setError('memory-candidate-feedback',new Error('검토한 내용과 승인이 일치하지 않습니다. 다시 검토하세요.'));try{await api('/api/personal-space/memory-candidates/request',body);memoryCandidateReview=null;selectedCandidateId='';$('memory-candidate-feedback').textContent='검토한 내용을 기억으로 저장했습니다.';await loadMemoryCandidates();await refreshLoadedRecords();await refresh();}catch(error){setError('memory-candidate-feedback',error);}});
  actions.append(accept);
  detail.append(element('p',`이 승인은 ${safeTime(memoryCandidateReview.approval.expires_at)}까지만 쓸 수 있고, 그 사이 기억이 바뀌면 무효가 됩니다.`,'technical'));
 }
 const reject=element('button','거부');reject.type='button';
 reject.onclick=()=>busy(reject,async()=>{const body=memoryCandidateDecisionBody(memoryCandidateReview,'reject');if(!body)return setError('memory-candidate-feedback',new Error('검토한 후보를 다시 확인하세요.'));try{await api('/api/personal-space/memory-candidates/request',body);memoryCandidateReview=null;selectedCandidateId='';$('memory-candidate-feedback').textContent='이 후보를 거부했습니다. 기억으로 저장하지 않습니다.';await loadMemoryCandidates();await refresh();}catch(error){setError('memory-candidate-feedback',error);}});
 actions.append(reject);detail.append(actions);
}
$('memory-candidates').ontoggle=()=>{if(!$('memory-candidates').open){memoryCandidateObservedCount=null;return;}memoryCandidateObservedCount=lastSpace?.memory_candidate_count??null;void loadMemoryCandidates();};

function rememberWorkspaceResultSummary(workspace,updated){workspaceResultSummaries.set(workspace.id,{updated,summary:workspaceResultSummary(workspace)});}
async function loadWorkspaceResultSummaries(workspaces){await Promise.all((workspaces||[]).map(async workspace=>{const cached=workspaceResultSummaries.get(workspace.id);if(cached&&cached.updated===workspace.updated)return;try{const detail=await api('/api/workspaces/'+encodeURIComponent(workspace.id));const current=lastHome?.workspaces?.find(item=>item.id===workspace.id);if(current&&current.updated===workspace.updated){rememberWorkspaceResultSummary(detail,workspace.updated);renderWorkspaces(lastHome,lastState);}}catch(_error){}}));}
async function selectWorkspace(id){selectedWorkspaceId=id;const request=++workspaceDetailSequence;document.querySelectorAll('.workspace-row').forEach(row=>row.classList.toggle('selected',row.dataset.workspaceId===id));try{const workspace=await api('/api/workspaces/'+encodeURIComponent(id));if(shouldRenderWorkspaceDetail(selectedWorkspaceId,id,request,workspaceDetailSequence)){rememberWorkspaceResultSummary(workspace,lastHome?.workspaces?.find(item=>item.id===id)?.updated);renderWorkspaceDetail(workspace);renderWorkspaces(lastHome,lastState);}}catch(error){if(shouldRenderWorkspaceDetail(selectedWorkspaceId,id,request,workspaceDetailSequence))setError('workspace-feedback',error);}}
function renderWorkspaceDetail(workspace){const detail=$('workspace-detail');detail.replaceChildren(element('h3',workspace.title),element('p',workspace.purpose||'설명 없음','muted'));const results=workspace.results||[];detail.append(element('h4','저장된 결과'));for(const result of results)detail.append(element('p',result.content||'내용 없음','workspace-result'));if(!results.length)detail.append(element('p','아직 저장된 결과가 없습니다.','muted'));const candidates=workspaceSaveCandidates(lastState?.jobs,workspace.id,workspace.saved_job_ids);for(const job of candidates){const button=element('button','완료 결과 저장');button.type='button';button.onclick=()=>busy(button,async()=>{const workspaceId=workspace.id,request=++workspaceDetailSequence;recordLoadSequence++;try{const saved=await api('/api/workspaces/'+encodeURIComponent(workspaceId)+'/save-result',{job_id:job.id}),current=lastHome?.workspaces?.find(item=>item.id===workspaceId);rememberWorkspaceResultSummary(saved,current?.updated);if(shouldRenderWorkspaceDetail(selectedWorkspaceId,workspaceId,request,workspaceDetailSequence))renderWorkspaceDetail(saved);$('workspace-feedback').textContent='완료 결과를 프로젝트에 저장했습니다.';await loadRecords();renderWorkspaces(lastHome,lastState);}catch(error){setError('workspace-feedback',error);}});detail.append(element('p',`${job.workspace_id?'이 프로젝트':'미지정 작업'} · ${job.response||job.message||'완료된 작업'}`),button);}}
function renderWorkspaces(home,state){const list=$('workspace-list'),workspaces=home?.workspaces||[],summaries=workspaces.map(workspace=>workspaceResultSummaries.get(workspace.id)?.summary?.label||'완료 결과 확인 중…'),fingerprint=JSON.stringify([workspaces,summaries]);if(list.dataset.state===fingerprint)return;list.dataset.state=fingerprint;list.replaceChildren();if(selectedWorkspaceId&&!workspaces.some(item=>item.id===selectedWorkspaceId))selectedWorkspaceId='';workspaces.forEach((workspace,index)=>{const row=element('button',undefined,'workspace-row'+(workspace.id===selectedWorkspaceId?' selected':''));row.type='button';row.dataset.workspaceId=workspace.id;row.append(element('strong',workspace.title),element('span',summaries[index]));row.onclick=()=>selectWorkspace(workspace.id);list.append(row);});if(!workspaces.length)list.append(element('p','프로젝트가 없습니다.','muted'));}
$('workspace-form').onsubmit=event=>{event.preventDefault();busy(event.submitter,async()=>{try{await api('/api/workspaces',{title:$('workspace-title').value,purpose:$('workspace-purpose').value});$('workspace-title').value='';$('workspace-purpose').value='';$('workspace-feedback').textContent='프로젝트를 만들었습니다.';await refresh();}catch(error){setError('workspace-feedback',error);}});};

function renderContext(inbox){if(!inbox)return;if(!contextDraftDirty&&!['context-text','context-url'].includes(document.activeElement?.id)){$('context-text').checked=!!inbox.sources?.text;$('context-url').checked=!!inbox.sources?.url;}let warning=$('context-sharing-warning');if(!warning){warning=element('p');warning.id='context-sharing-warning';$('context-telegram-policy').after(warning);}warning.textContent=inbox.sharing_requires_policy_and_per_request_approval?'이 정책을 허용해도 각 Telegram 작업마다 공유 승인이 필요합니다.':'';const list=$('context-items');list.replaceChildren();for(const item of inbox.items||[]){const row=element('div',undefined,'record-row');row.append(element('span',`${item.source_kind} · ${safeTime(item.captured_at)} · ${safeTime(item.expires_at)} 만료`));const remove=element('button','삭제');remove.type='button';remove.onclick=()=>busy(remove,async()=>{try{await api('/api/context-inbox/delete',{id:item.id});await refresh();}catch(error){setError('context-feedback',error);}});row.append(remove);list.append(row);}if(!(inbox.items||[]).length)list.append(element('p','저장된 임시 자료가 없습니다.','muted'));}
$('context-config').onsubmit=event=>{event.preventDefault();busy(event.submitter,async()=>{try{await api('/api/context-inbox/config',{sources:{text:$('context-text').checked,url:$('context-url').checked}});contextDraftDirty=false;$('context-feedback').textContent='수집 설정을 저장했습니다.';await refresh();}catch(error){setError('context-feedback',error);}});};
['context-text','context-url'].forEach(id=>$(id).onchange=()=>{contextDraftDirty=true;});
$('context-capture').onsubmit=event=>{event.preventDefault();busy(event.submitter,async()=>{try{await api('/api/context-inbox/capture',{source_kind:$('context-kind').value,content:$('context-content').value});$('context-content').value='';$('context-feedback').textContent='임시 자료를 로컬에 저장했습니다.';await refresh();}catch(error){setError('context-feedback',error);}});};
$('context-telegram-policy').onclick=()=>busy($('context-telegram-policy'),async()=>{try{await api('/api/context-inbox/telegram-policy',{approved:true});$('context-feedback').textContent='현재 모델의 Telegram 공유 정책을 승인했습니다.';await refresh();}catch(error){setError('context-feedback',error);}});

$('roots-form').onsubmit=event=>{event.preventDefault();busy(event.submitter,async()=>{try{await api('/api/files/roots',{paths:$('root-paths').value.split('\n').map(value=>value.trim()).filter(Boolean)});invalidateRootsLoad();$('roots-feedback').textContent='참고 폴더를 연결했습니다.';await refresh();}catch(error){setError('roots-feedback',error);}});};
$('file-workspace-form').onsubmit=event=>{event.preventDefault();busy(event.submitter,async()=>{try{await api('/api/file-workspace',{references:$('file-reference-paths').value.split('\n').map(value=>value.trim()).filter(Boolean),workspace:$('file-workspace-path').value.trim()});invalidateFileWorkspaceLoad();$('file-workspace-feedback').textContent='파일 위치를 저장했습니다.';await refresh();}catch(error){setError('file-workspace-feedback',error);}});};
function renderDocumentBoundary(boundary){const box=$('document-boundary');box.replaceChildren();if(!boundary)return;if(!boundary.external_model){box.append(element('p','문서 발췌문은 현재 외부 모델 경로로 전송되지 않습니다.'));return;}if(boundary.approved){box.append(element('p','현재 모델과 폴더에 대한 문서 공유가 승인되었습니다.'));return;}box.append(element('p','외부 AI에 필요한 문서 발췌문을 보내기 전 승인이 필요합니다.'));const button=element('button','문서 발췌문 전송 승인');button.onclick=()=>busy(button,async()=>{try{await api('/api/documents/approval',{approved:true});await refresh();}catch(error){setError('roots-feedback',error);}});box.append(button);}

function renderTelegram(settings){const tg=settings.telegram||{},box=$('telegram-current');box.replaceChildren(element('strong','Telegram'));if(tg.enabled){box.append(element('p',tg.paired?`연결됨 · @${tg.username||'개인 봇'}`:'봇 설정됨 · 소유자 연결 대기'));if(!telegramDraftOpen)$('telegram-form').hidden=true;$('telegram-change').textContent='연결 변경';}else{box.append(element('p','연결되지 않음'));$('telegram-change').textContent='Telegram 연결 설정';}$('telegram-status').textContent=settings.telegram_status?.message||'';$('disconnect').hidden=!tg.enabled;$('new-pair').hidden=!tg.enabled;if(tg.paired)$('telegram-pair').hidden=true;}
function renderCapabilityPreview(row,preview){let review=row.querySelector('.capability-preview');if(review)review.remove();review=element('div',undefined,'capability-preview');review.append(element('p',preview.effect||`${preview.target} ${preview.action}`));const actions=element('div',undefined,'button-row'),confirm=element('button','확인'),cancel=element('button','취소');confirm.type=cancel.type='button';confirm.onclick=()=>busy(confirm,async()=>{try{await api('/api/settings/request',{operation:'confirm',draft_id:preview.id,digest:preview.digest});$('capability-feedback').textContent='기능 권한 상태를 변경했습니다.';await refresh();}catch(error){setError('capability-feedback',error);}});cancel.onclick=()=>busy(cancel,async()=>{try{await api('/api/settings/request',{operation:'cancel',draft_id:preview.id,digest:preview.digest});review.remove();$('capability-feedback').textContent='변경을 취소했습니다.';}catch(error){setError('capability-feedback',error);}});actions.append(confirm,cancel);review.append(actions);row.append(review);}
// Owner-visible words for the four contract states.  An unknown value is
// reported as unknown rather than guessed as connected: a wrong 'connected'
// here would tell the owner an authorization exists that does not.
const CONNECTOR_STATES={disconnected:'연결 안 됨',connected:'연결됨',reauth_required:'다시 인증 필요',blocked:'차단됨'};
// The connect action is a plain same-origin navigation, not an api() call:
// /google-gmail answers 303 to Google, which fetch would follow cross-origin
// and discard.  The href stays relative so the owner-session cookie, which is
// SameSite=Strict and host-scoped, travels whether AgentOS was opened at
// 127.0.0.1 or localhost.  Drawing the link grants nothing; the route still
// requires that session and still refuses a tunnel host.
function renderConnectors(connectors){const box=$('connector-controls');if(!box)return;const rows=connectors||[],fingerprint=JSON.stringify(rows);if(box.dataset.state===fingerprint)return;box.dataset.state=fingerprint;box.replaceChildren();for(const connector of rows){const row=element('div',undefined,'capability-row');row.append(element('strong',connector.label||connector.connector_id),element('p',`${CONNECTOR_STATES[connector.state]||'상태 알 수 없음'} · ${(connector.required_scopes||[]).join(', ')||'요청 권한 없음'}`));if(connector.connect_path&&connector.state!=='blocked'){const link=element('a',connector.state==='connected'?'다시 연결':'연결하기','button-link');link.href=connector.connect_path;link.rel='noreferrer';row.append(link);}box.append(row);}if(!rows.length)box.append(element('p','이 설치에 구성된 외부 연결이 없습니다.','muted'));}
function renderCapabilities(model){const box=$('capability-controls'),fingerprint=JSON.stringify(model||{});if(box.dataset.state===fingerprint)return;box.dataset.state=fingerprint;box.replaceChildren();for(const capability of model?.capabilities||[]){const row=element('div',undefined,'capability-row');row.append(element('strong',capability.id),element('p',`${capability.state||'상태 알 수 없음'} · ${capability.recovery||'복구 안내 없음'}`));for(const action of capabilityActions(capability)){const labels={pause:'일시 정지',disconnect:'연결 해제',resume:'다시 시작'},button=element('button',labels[action]);button.type='button';button.onclick=()=>busy(button,async()=>{try{const response=await api('/api/settings/request',{operation:'draft',intent:`${capability.id} ${action}`});renderCapabilityPreview(row,response.preview);}catch(error){setError('capability-feedback',error);}});row.append(button);}box.append(row);}if(!(model?.capabilities||[]).length)box.append(element('p','검토된 로컬 기능이 없습니다.','muted'));}
$('telegram-change').onclick=()=>{telegramDraftOpen=$('telegram-form').hidden;$('telegram-form').hidden=!telegramDraftOpen;if(telegramDraftOpen)$('telegram-token').focus();};
function showPair(data){$('pair-link').href=data.url;$('telegram-pair').hidden=false;$('telegram-token').value='';}
$('telegram-form').onsubmit=event=>{event.preventDefault();busy(event.submitter,async()=>{try{showPair(await api('/api/telegram',{token:$('telegram-token').value}));telegramDraftOpen=false;await refresh();}catch(error){setError('telegram-status',error);}});};
$('new-pair').onclick=async()=>{try{showPair(await api('/api/telegram/pair',{}));}catch(error){setError('telegram-status',error);}};
$('disconnect').onclick=async()=>{try{await api('/api/telegram/disconnect',{});telegramDraftOpen=false;$('telegram-pair').hidden=true;await refresh();}catch(error){setError('telegram-status',error);}};

function renderDiagnostics(state,tasks){const events=state?.tool_events||[],current=events[0];$('tool-status').textContent=current?`${current.tool} · ${current.status}`:'관찰된 도구 활동이 없습니다.';const list=$('tool-history');list.replaceChildren();events.slice(0,20).forEach(event=>list.append(element('p',`${safeTime(event.created)} · ${event.tool} · ${event.status}`)));const hidden=(tasks||[]).filter(isDiagnosticTask).length;$('diagnostic-activity').textContent=`기본 작업 목록에서 구분한 연결·진단 활동 ${hidden}개`;}

async function refresh(){
 if(!authenticated)return;if(refreshing){refreshQueued=true;return;}refreshing=true;const requestedModelRevision=modelLoadRevision,requestedRootsRevision=rootsLoadRevision,requestedFileWorkspaceRevision=fileWorkspaceLoadRevision;$('task-refresh-state').textContent='확인 중…';
 try{
  const [summary,home,state,space]=await Promise.all([api('/api/tasks'),api('/api/home'),api('/api/state'),api('/api/personal-space')]);const previousSelected=taskProgress?.tasks?.find(task=>task.id===selectedTaskId);lastHome=home;lastState=state;lastSpace=space;taskProgress=mergeTaskProgress(summary,taskProgress,state.jobs);renderTasks();const selected=taskProgress.tasks.find(task=>task.id===selectedTaskId);refreshSelectedTaskDetail(previousSelected,selected,id=>selectTask(id,false));renderRecords();renderMemoryCandidateSummary(space);if(activeView==='records')void refreshLoadedRecords();renderWorkspaces(home,state);loadWorkspaceResultSummaries(home.workspaces);
  const settings=state.settings||{};renderExecutionConnection(settings);renderSubscriptionEngines(settings.subscription_engines);renderTelegram(settings);renderCapabilities(settings.conversation_settings);renderConnectors(settings.connectors);renderContext(settings.context_inbox);renderDocumentBoundary(settings.document_boundary);renderDiagnostics(state,taskProgress.tasks);$('runtime-badge').textContent=home.state==='working'?'작업 중':home.state==='attention'?'확인 필요':'준비됨';
  if(!modelLoaded){if(requestedModelRevision===modelLoadRevision){const model=settings.model||{};if(model.provider){$('provider').value=displayProvider(model);$('endpoint').value=model.endpoint||'';$('model-name').value=model.model||'';activeModelDestination=[displayProvider(model),normalizeEndpoint(model.endpoint)].join('|');}$('endpoint-help').textContent=providers[$('provider').value]?.help||'';$('key-hint').textContent=settings.has_api_key?'키가 저장되어 있습니다. 빈칸은 같은 연결의 키를 유지합니다.':'키는 대화 이력과 분리해 저장합니다.';modelLoaded=true;}}
  if(!rootsLoaded&&requestedRootsRevision===rootsLoadRevision){$('root-paths').value=(settings.file_roots||[]).map(item=>item.path).join('\n');rootsLoaded=true;}
  if(!fileWorkspaceLoaded&&requestedFileWorkspaceRevision===fileWorkspaceLoadRevision){$('file-reference-paths').value=(settings.file_workspace?.references||[]).map(item=>item.path).join('\n');$('file-workspace-path').value=settings.file_workspace?.workspace||'';fileWorkspaceLoaded=true;}
  $('task-refresh-state').textContent='방금 확인';$('global-error').textContent='';
 }catch(error){setError('global-error',error);$('task-refresh-state').textContent='새로 고치지 못함';}finally{refreshing=false;if(refreshQueued){refreshQueued=false;void refresh();}}
}

async function status(){
 let state=await api('/api/status');if(!state.claimed){await api('/api/claim',{code:bootstrap});state=await api('/api/status');}claimed=state.claimed;authenticated=state.authenticated;if(!authenticated&&state.local_access){await api('/api/local-login',{});authenticated=true;}
 $('welcome').hidden=authenticated;$('management').hidden=!authenticated;$('logout').hidden=!authenticated||state.local_access;$('auth-title').textContent=claimed?'다시 만나서 반갑습니다.':'나만의 AgentOS를 시작하세요.';$('auth-step').textContent=claimed?'개인 환경 로그인':'처음 시작하기';$('auth-help').textContent=claimed?'설정한 비밀번호로 로그인하세요.':'이 Mac에서 사용할 개인 환경을 준비합니다.';$('auth-submit').textContent=claimed?'로그인':'바로 시작하기';$('password').required=claimed;$('password-option').open=claimed;$('password').minLength=claimed?1:12;$('password').autocomplete=claimed?'current-password':'new-password';
 if(authenticated){const route=routeFromLocation();activeView=route.view;activeSettings=route.settings;navigate(activeView,activeSettings,{replace:true});restoreOpenRouterFlow();await refresh();await loadRecords();await finishOpenRouter();}
}
$('auth-form').onsubmit=event=>{event.preventDefault();$('auth-error').textContent='';busy($('auth-submit'),async()=>{try{await api(claimed?'/api/login':'/api/claim',{password:$('password').value,code:bootstrap});bootstrap='';$('password').value='';await status();}catch(error){setError('auth-error',error);}});};
$('logout').onclick=async()=>{try{await api('/api/logout',{});invalidateModelLoad();invalidateRootsLoad();invalidateFileWorkspaceLoad();await status();}catch(error){setError('global-error',error);}};

$('connect-openrouter').onclick=async()=>{const popup=window.open('about:blank','agentos-openrouter');try{const bytes=crypto.getRandomValues(new Uint8Array(48)),verifier=btoa(String.fromCharCode(...bytes)).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const digest=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(verifier)),challenge=btoa(String.fromCharCode(...new Uint8Array(digest))).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');const state=crypto.randomUUID(),callback=location.origin+'/?state='+encodeURIComponent(state),url='https://openrouter.ai/auth?'+new URLSearchParams({callback_url:callback,code_challenge:challenge,code_challenge_method:'S256'});localStorage.setItem('openrouter-flow',JSON.stringify({verifier,state,url,expires:Date.now()+600000}));$('resume-openrouter').hidden=false;if(popup)popup.location.href=url;}catch(error){setError('easy-feedback',error);}};
function restoreOpenRouterFlow(){const flow=parseOpenRouterFlow(localStorage.getItem('openrouter-flow'));if(!flow)localStorage.removeItem('openrouter-flow');$('resume-openrouter').hidden=!flow;return flow;}
async function finishOpenRouter(){const params=new URLSearchParams(location.search);if(!params.has('code'))return;const flow=restoreOpenRouterFlow();history.replaceState(null,'',location.pathname+'#settings/ai');navigate('settings','ai');try{if(!flow||flow.state!==params.get('state'))throw new Error('연결 시간이 지났습니다. 다시 시작하세요.');await api('/api/openrouter/connect',{code:params.get('code'),verifier:flow.verifier});localStorage.removeItem('openrouter-flow');$('resume-openrouter').hidden=true;if(window.opener&&!window.opener.closed){window.opener.postMessage({type:'agentos-openrouter-connected'},location.origin);window.close();return;}invalidateModelLoad();$('api-key').value='';invalidateModelDraft('연결 결과가 바뀌었습니다. 적용 전에 다시 테스트하세요.');$('easy-feedback').textContent='OpenRouter 연결 결과를 저장했습니다.';await refresh();}catch(error){setError('easy-feedback',error);}}
window.addEventListener('message',event=>{if(!isOpenRouterCompletion(event,location.origin))return;localStorage.removeItem('openrouter-flow');$('resume-openrouter').hidden=true;invalidateModelLoad();$('api-key').value='';invalidateModelDraft('연결 결과가 바뀌었습니다. 적용 전에 다시 테스트하세요.');$('easy-feedback').textContent='OpenRouter 연결 결과를 저장했습니다.';void refresh();});
$('resume-openrouter').onclick=()=>{const flow=restoreOpenRouterFlow();if(flow)window.open(flow.url,'agentos-openrouter');else $('connect-openrouter').click();};
$('load-free-models').onclick=()=>busy($('load-free-models'),async()=>{try{const data=await api('/api/openrouter/models',{}),list=$('free-model-list');list.replaceChildren();for(const model of data.models||[]){const button=element('button',`${model.name} · ${model.id}`);button.type='button';button.onclick=()=>applyModelPreset({provider:'compatible',endpoint:'https://openrouter.ai/api/v1',model:model.id},'선택한 모델을 적용하기 전에 테스트하세요.');list.append(button);}if(!(data.models||[]).length)list.append(element('p','표시할 모델이 없습니다.'));}catch(error){setError('easy-feedback',error);}});
$('find-local').onclick=()=>busy($('find-local'),async()=>{try{const data=await api('/api/ollama/models',{}),list=$('local-models');list.replaceChildren();for(const model of data.models||[]){const button=element('button',model.name);button.type='button';button.onclick=()=>applyModelPreset({provider:'ollama',endpoint:'http://127.0.0.1:11434',model:model.name},'선택한 로컬 모델을 적용하기 전에 테스트하세요.');list.append(button);}$('local-help').textContent=(data.models||[]).length?'모델을 선택한 뒤 테스트하세요.':'실행 중이지만 설치된 모델이 없습니다.';}catch(_error){$('local-help').textContent='실행 중인 Ollama를 찾지 못했습니다.';}});

status().catch(error=>setError('global-error',error));
setInterval(()=>{if(authenticated)refresh();},2000);
}
